Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2022-05, with the labels that each got.

#536 [v2] Make the createApp API idiomatic for Express, fix service-worker loading.
  packages/pwa-kit-cli/src/configs/webpack/config-names.js
  packages/pwa-kit-cli/src/configs/webpack/config.js
  packages/pwa-kit-cli/src/ssr/server/build-dev-server.js
  packages/pwa-kit-cli/src/ssr/server/build-dev-server.test.js
  packages/pwa-kit-runtime/src/ssr/server/build-remote-server.js
  packages/pwa-kit-runtime/src/ssr/server/express.js
  packages/pwa-kit-runtime/src/ssr/server/express.test.js
  packages/template-retail-react-app/app/ssr.js
  packages/template-typescript-minimal/app/ssr.js
Labels: BUG P1, blocking

#558 Security Patches for Mobify Release v1.20.x
  lerna.json
  packages/commerce-integrations/package-lock.json
  packages/commerce-integrations/package.json
  packages/connector/package-lock.json
  packages/connector/package.json
  packages/documentation-theme/package-lock.json
  packages/documentation-theme/package.json
  packages/generator/package-lock.json
  packages/generator/package.json
  packages/progressive-web-sdk/CHANGELOG.md
  packages/progressive-web-sdk/package-lock.json
  packages/progressive-web-sdk/package.json
  packages/pwa/package-lock.json
  packages/pwa/package.json
  packages/test-framework/package-lock.json
  packages/test-framework/package.json
Labels: cla:signed

#559 Security Patches for Mobify Release v2.4.x
  lerna.json
  package-lock.json
  package.json
  packages/commerce-integrations/CHANGELOG.md
  packages/commerce-integrations/package-lock.json
  packages/commerce-integrations/package.json
  packages/create-app/package-lock.json
  packages/create-app/package.json
  packages/progressive-web-sdk/CHANGELOG.md
  packages/progressive-web-sdk/package-lock.json
  packages/progressive-web-sdk/package.json
  packages/pwa/package-lock.json
  packages/pwa/package.json
Labels: cla:signed

#577 Generator: pin versions of pwa-kit-* packages
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
Labels: ready for review

#578 Add comment explaining dev server import.
  packages/pwa-kit-runtime/src/ssr/server/express.js
Labels: ready for review

#574 [V2][Generator] Add `typescript-minimal` and `typescript-minimal-test-project` presets
  .circleci/config.yml
  packages/pwa-kit-create-app/scripts/build.js
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
Labels: ready for review

#570 Wjh/translations docs
  .github/PULL_REQUEST_TEMPLATE.md
  packages/template-retail-react-app/app/translations/README.md
Labels: ready for review

#590 [V2] Clarify that service worker does not have to be hosted at the root
  packages/pwa-kit-runtime/src/ssr/server/build-remote-server.js
  packages/template-retail-react-app/app/main.jsx
  packages/template-typescript-minimal/app/ssr.js
Labels: ready for review

#568 [V2] Add favicon for `template-retail-react-app`
  packages/pwa-kit-runtime/src/ssr/server/build-remote-server.js
  packages/pwa-kit-runtime/src/ssr/server/express.test.js
  packages/template-express-minimal/app/ssr.js
  packages/template-retail-react-app/app/ssr.js
  packages/template-typescript-minimal/app/ssr.js
  packages/template-typescript-minimal/package.json
Labels: ready for review

#617 Return clone instead of modifying original runtime.
  packages/pwa-kit-runtime/src/ssr/server/express.js
  packages/pwa-kit-runtime/src/ssr/server/express.test.js
Labels: ready for review

#619 Fix `pwa-kit-dev` "Mobify" references
  packages/pwa-kit-dev/CHANGELOG.md
  packages/pwa-kit-dev/scripts/utils.js
  packages/pwa-kit-dev/scripts/utils.test.js
Labels: ready for review

#607 [V2] Retail react app: have a shorter default cache time
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/app/pages/home/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/app/pages/product-list/index.jsx
Labels: ready for review

#550 Improve test coverage
  packages/internal-lib-build/.eslintignore
  packages/pwa-kit-dev/.eslintignore
  packages/pwa-kit-dev/.prettierignore
  packages/pwa-kit-dev/jest.config.js
  packages/pwa-kit-dev/package-lock.json
  packages/pwa-kit-dev/package.json
  packages/pwa-kit-dev/src/ssr/server/build-dev-server.js
  packages/pwa-kit-dev/src/ssr/server/build-dev-server.test.js
  packages/pwa-kit-react-sdk/.eslintignore
  packages/pwa-kit-react-sdk/.prettierignore
  packages/pwa-kit-react-sdk/jest.config.js
  packages/pwa-kit-react-sdk/src/ssr/universal/components/app-error-boundary/index.test.js
  packages/pwa-kit-react-sdk/src/ssr/universal/utils.server.test.js
  packages/pwa-kit-runtime/.eslintignore
  packages/pwa-kit-runtime/.prettierignore
  packages/pwa-kit-runtime/jest.config.js
  packages/pwa-kit-runtime/src/ssr/server/express.test.js
  packages/pwa-kit-runtime/src/ssr/server/test_fixtures/server-renderer.js
  packages/template-express-minimal/app/ssr.js
  packages/template-express-minimal/app/ssr.test.js
  packages/template-express-minimal/jest.config.js
  packages/template-express-minimal/package-lock.json
  packages/template-express-minimal/package.json
  packages/template-typescript-minimal/app/ssr.js
  packages/template-typescript-minimal/jest.config.js
Labels: ready for review

#622 Update Circle CI config
  .circleci/config.yml
Labels: ready for review

#616 [V2] Clearing cache and service worker when starting dev server
  packages/pwa-kit-dev/src/ssr/server/build-dev-server.js
  packages/pwa-kit-dev/src/ssr/server/loading-screen/index.html
Labels: ready for review

#624 Fix generator jobs failing
  .circleci/config.yml
  packages/pwa-kit-create-app/scripts/create-mobify-app-dev.js
Labels: ready for review

#623 Wjh/upgrade deps
  package.json
  packages/internal-lib-build/package-lock.json
  packages/internal-lib-build/package.json
  packages/pwa-kit-create-app/package-lock.json
  packages/pwa-kit-create-app/package.json
  packages/pwa-kit-dev/package.json
  packages/pwa-kit-runtime/package-lock.json
  packages/pwa-kit-runtime/package.json
  packages/pwa-kit-runtime/src/ssr/server/express.test.js
  packages/template-retail-react-app/package.json
  packages/template-typescript-minimal/package.json
Labels: ready for review

#620 Flex the width for the notifications badge
  packages/template-retail-react-app/app/theme/components/base/badge.js
Labels: cla:signed

#628 Add support for custom build directory
  packages/pwa-kit-dev/CHANGELOG.md
  packages/pwa-kit-dev/bin/pwa-kit-dev.js
  packages/pwa-kit-dev/package.json
  packages/pwa-kit-dev/src/configs/webpack/config.js
Labels: ready for review

#630 Client-side hot reloading / HMR
  packages/pwa-kit-dev/CHANGELOG.md
  packages/pwa-kit-dev/bin/pwa-kit-dev.js
  packages/pwa-kit-dev/package-lock.json
  packages/pwa-kit-dev/package.json
  packages/pwa-kit-dev/src/configs/webpack/config.js
  packages/pwa-kit-dev/src/ssr/server/build-dev-server.js
  packages/pwa-kit-react-sdk/src/ssr/server/react-rendering.js
  packages/pwa-kit-react-sdk/src/ssr/universal/utils.js
  packages/template-typescript-minimal/package.json
Labels: ready for review
