Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2022-01, with the labels that each got.

#271 Add legal notice to README
  README.md
Labels: ready for review

#268 renamed mobify to pwa kit and project folder.
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
Labels: ready for review

#269 Cosmetic changes for mobify name and docs urls
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
  packages/pwa-kit-react-sdk/bin/save-credentials.js
  packages/pwa-kit-react-sdk/bin/upload.js
  packages/pwa-kit-react-sdk/scripts/upload.js
  packages/pwa-kit-react-sdk/scripts/upload.test.js
  packages/pwa-kit-react-sdk/scripts/utils.js
  packages/pwa-kit-react-sdk/src/ssr/server/express.js
  scripts/check-version.js
  scripts/smoke-test-npm-scripts.js
Labels: ready for review

#286 Edit URL customization copy
  packages/pwa-kit-create-app/README.md
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
  packages/pwa-kit-react-sdk/README.md
  packages/pwa-kit-react-sdk/src/ssr/server/express.js
  packages/pwa/README.md
  packages/pwa/app/commerce-api/einstein.js
  packages/pwa/app/pages/home/data.js
  packages/pwa/app/pages/home/index.jsx
  packages/pwa/app/translations/en-GB.json
Labels: ready for review

#222 Add to Cart will remain active unless the item is out of stock
  packages/pwa/app/partials/product-view/index.jsx
  packages/pwa/app/translations/compiled/en-GB.json
  packages/pwa/app/translations/en-GB.json
Labels: ready for review, cla:signed, contribution

#285 Allow generating test-project with correct Einstein's site id
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
Labels: ready for review

#297 Update create-app's CHANGELOG.md
  packages/pwa-kit-create-app/CHANGELOG.md
Labels: ready for review

#300 Deprecate create-hash-manifest script
  packages/pwa-kit-react-sdk/scripts/create-hash-manifest.js
Labels: ready for review, BUG P3

#302 Support for NPM 7 & 8
  .circleci/config.yml
  package.json
  packages/pwa-kit-react-sdk/CHANGELOG.md
  packages/pwa-kit-react-sdk/package.json
  packages/pwa-kit-react-sdk/scripts/prepare-dist.js
  scripts/bootstrap.js
Labels: ready for review

#326 Fix server error handling for unrecoverable errors
  packages/pwa-kit-react-sdk/CHANGELOG.md
  packages/pwa-kit-react-sdk/src/ssr/server/react-rendering.js
  packages/pwa-kit-react-sdk/src/ssr/server/react-rendering.test.js
Labels: ready for review

#317 Reduce PWA's dependencies
  .circleci/config.yml
  packages/pwa/CHANGELOG.md
  packages/pwa/app/pages/checkout/index.test.js
  packages/pwa/package-lock.json
  packages/pwa/package.json
  packages/pwa/scripts/utils.js
Labels: ready for review

#325 Generator creates a project with a singe-locale
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/pwa-kit-create-app/assets/pwa/l10n.config.js
  packages/pwa-kit-create-app/assets/pwa/pwa-kit.config.json
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
  packages/pwa/app/components/drawer-menu/index.test.js
  packages/pwa/app/components/header/index.test.js
  packages/pwa/app/components/image-gallery/index.test.js
  packages/pwa/app/components/link/index.test.js
  packages/pwa/app/components/search/index.test.js
  packages/pwa/app/hooks/use-auth-modal.test.js
  packages/pwa/app/pages/account/index.test.js
  packages/pwa/app/pages/account/orders.test.js
  packages/pwa/app/pages/checkout/index.test.js
  packages/pwa/app/pages/login/index.test.js
  packages/pwa/app/pages/registration/index.test.jsx
  packages/pwa/app/pages/reset-password/index.test.jsx
  packages/pwa/app/translations/compiled/en-US.json
  packages/pwa/app/translations/en-US.json
  packages/pwa/app/utils/locale.test.js
  packages/pwa/app/utils/test-utils.js
Labels: ready for review

#322 Generator with demo settings
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
Labels: ready for review
