Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2022-10, with the labels that each got.

#718 Handle validation error from commerce-sdk-isomorphic
  packages/commerce-sdk-react/src/hooks/ShopperProducts/query.test.tsx
  packages/commerce-sdk-react/src/hooks/ShopperProducts/query.ts
  packages/commerce-sdk-react/src/test-utils.tsx
  packages/test-commerce-sdk-react/app/pages/home.tsx
  packages/test-commerce-sdk-react/app/pages/query-errors.tsx
  packages/test-commerce-sdk-react/app/routes.tsx
Labels: ready for review

#743 Add tests for optional apiClient configs like headers and fetchOptions
  packages/commerce-sdk-react/mock-responses/api-clients-optional-config-are-passed-properly.json
  packages/commerce-sdk-react/src/provider.test.tsx
  packages/commerce-sdk-react/src/test-utils.tsx
Labels: ready for review

#741 Dynamic footer Copyright date
  packages/template-retail-react-app/app/components/footer/index.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/checkout-footer.jsx
  packages/template-retail-react-app/app/translations/compiled/de-DE.json
  packages/template-retail-react-app/app/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/translations/compiled/en-US.json
  packages/template-retail-react-app/app/translations/compiled/en-XB.json
  packages/template-retail-react-app/app/translations/compiled/es-MX.json
  packages/template-retail-react-app/app/translations/compiled/fr-FR.json
  packages/template-retail-react-app/app/translations/compiled/it-IT.json
  packages/template-retail-react-app/app/translations/compiled/ja-JP.json
  packages/template-retail-react-app/app/translations/compiled/ko-KR.json
  packages/template-retail-react-app/app/translations/compiled/pt-BR.json
  packages/template-retail-react-app/app/translations/compiled/zh-CN.json
  packages/template-retail-react-app/app/translations/compiled/zh-TW.json
  packages/template-retail-react-app/app/translations/de-DE.json
  packages/template-retail-react-app/app/translations/en-GB.json
  packages/template-retail-react-app/app/translations/en-US.json
  packages/template-retail-react-app/app/translations/es-MX.json
  packages/template-retail-react-app/app/translations/fr-FR.json
  packages/template-retail-react-app/app/translations/it-IT.json
  packages/template-retail-react-app/app/translations/ja-JP.json
  packages/template-retail-react-app/app/translations/ko-KR.json
  packages/template-retail-react-app/app/translations/pt-BR.json
  packages/template-retail-react-app/app/translations/zh-CN.json
  packages/template-retail-react-app/app/translations/zh-TW.json
Labels: cla:signed

#759 Shopper promotions hooks
  packages/commerce-sdk-react/mock-responses/usepromotions-returns-data.json
  packages/commerce-sdk-react/mock-responses/usepromotions-returns-error.json
  packages/commerce-sdk-react/mock-responses/usepromotionsforcampaign-returns-data.json
  packages/commerce-sdk-react/mock-responses/usepromotionsforcampaign-returns-error.json
  packages/commerce-sdk-react/src/hooks/ShopperProducts/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperPromotions/query.test.tsx
  packages/commerce-sdk-react/src/hooks/ShopperPromotions/query.ts
  packages/test-commerce-sdk-react/app/pages/home.tsx
  packages/test-commerce-sdk-react/app/pages/use-promotions-for-campaign.tsx
  packages/test-commerce-sdk-react/app/pages/use-promotions.tsx
  packages/test-commerce-sdk-react/app/routes.tsx
Labels: ready for review

#760 Footer copyright: remove the remaining hardcoded year
  packages/template-retail-react-app/app/translations/compiled/de-DE.json
  packages/template-retail-react-app/app/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/translations/compiled/en-XB.json
  packages/template-retail-react-app/app/translations/compiled/es-MX.json
  packages/template-retail-react-app/app/translations/compiled/fr-FR.json
  packages/template-retail-react-app/app/translations/compiled/it-IT.json
  packages/template-retail-react-app/app/translations/compiled/ja-JP.json
  packages/template-retail-react-app/app/translations/compiled/ko-KR.json
  packages/template-retail-react-app/app/translations/compiled/pt-BR.json
  packages/template-retail-react-app/app/translations/compiled/zh-CN.json
  packages/template-retail-react-app/app/translations/compiled/zh-TW.json
  packages/template-retail-react-app/app/translations/de-DE.json
  packages/template-retail-react-app/app/translations/en-GB.json
  packages/template-retail-react-app/app/translations/es-MX.json
  packages/template-retail-react-app/app/translations/fr-FR.json
  packages/template-retail-react-app/app/translations/it-IT.json
  packages/template-retail-react-app/app/translations/ja-JP.json
  packages/template-retail-react-app/app/translations/ko-KR.json
  packages/template-retail-react-app/app/translations/pt-BR.json
  packages/template-retail-react-app/app/translations/zh-CN.json
  packages/template-retail-react-app/app/translations/zh-TW.json
Labels: ready for review

#769 [commerce-sdk-react] Multisite support
  packages/commerce-sdk-react/mock-responses/usecategories-returns-data.json
  packages/commerce-sdk-react/mock-responses/usecategories-returns-error.json
  packages/commerce-sdk-react/mock-responses/usecategory-returns-data.json
  packages/commerce-sdk-react/mock-responses/usecategory-returns-error.json
  packages/commerce-sdk-react/mock-responses/usecommerceapi-returns-a-set-of-api-clients.json
  packages/commerce-sdk-react/mock-responses/useproduct-returns-data.json
  packages/commerce-sdk-react/mock-responses/useproduct-returns-error.json
  packages/commerce-sdk-react/mock-responses/useproducts-returns-data.json
  packages/commerce-sdk-react/mock-responses/useproducts-returns-error.json
  packages/commerce-sdk-react/mock-responses/useproductsearch-returns-data.json
  packages/commerce-sdk-react/mock-responses/useproductsearch-returns-error.json
  packages/commerce-sdk-react/mock-responses/usepromotions-returns-data.json
  packages/commerce-sdk-react/mock-responses/usepromotions-returns-error.json
  packages/commerce-sdk-react/mock-responses/usepromotionsforcampaign-returns-data.json
  packages/commerce-sdk-react/mock-responses/usepromotionsforcampaign-returns-error.json
  packages/commerce-sdk-react/mock-responses/usesearchsuggestions-returns-data.json
  packages/commerce-sdk-react/mock-responses/usesearchsuggestions-returns-error.json
  packages/commerce-sdk-react/src/auth/index.test.ts
  packages/commerce-sdk-react/src/auth/index.ts
  packages/commerce-sdk-react/src/hooks/ShopperProducts/query.test.tsx
  packages/commerce-sdk-react/src/hooks/ShopperProducts/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperPromotions/query.test.tsx
  packages/commerce-sdk-react/src/hooks/ShopperSearch/query.test.tsx
  packages/commerce-sdk-react/src/hooks/ShopperSearch/query.ts
  packages/commerce-sdk-react/src/hooks/useConfig.ts
  packages/commerce-sdk-react/src/provider.test.tsx
  packages/commerce-sdk-react/src/provider.tsx
  packages/commerce-sdk-react/src/test-utils.tsx
  packages/test-commerce-sdk-react/app/components/_app-config/index.tsx
Labels: cla:signed

#766 ShopperOrders hooks & mutations
  packages/commerce-sdk-react/mock-responses/useorder-returns-data.json
  packages/commerce-sdk-react/mock-responses/useorder-returns-error.json
  packages/commerce-sdk-react/mock-responses/usepaymentmethodsfororder-returns-data.json
  packages/commerce-sdk-react/mock-responses/usepaymentmethodsfororder-returns-error.json
  packages/commerce-sdk-react/src/hooks/ShopperOrders/query.test.tsx
  packages/commerce-sdk-react/src/hooks/ShopperOrders/query.ts
  packages/commerce-sdk-react/src/test-utils.tsx
  packages/test-commerce-sdk-react/app/pages/home.tsx
  packages/test-commerce-sdk-react/app/pages/use-payment-methods.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-get-order.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-login-helper.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-orders.tsx
  packages/test-commerce-sdk-react/app/routes.tsx
Labels: wip

#762 ShopperCustomer hooks and mutations
  packages/commerce-sdk-react/mock-responses/usecategories-returns-data.json
  packages/commerce-sdk-react/mock-responses/usecategories-returns-error.json
  packages/commerce-sdk-react/mock-responses/usecategory-returns-data.json
  packages/commerce-sdk-react/mock-responses/usecategory-returns-error.json
  packages/commerce-sdk-react/mock-responses/usecustomer-returns-data.json
  packages/commerce-sdk-react/mock-responses/usecustomer-returns-error.json
  packages/commerce-sdk-react/mock-responses/usecustomeraddress-returns-data.json
  packages/commerce-sdk-react/mock-responses/usecustomeraddress-returns-error.json
  packages/commerce-sdk-react/mock-responses/usecustomerbaskets-returns-data.json
  packages/commerce-sdk-react/mock-responses/usecustomerbaskets-returns-error.json
  packages/commerce-sdk-react/mock-responses/usecustomerorders-returns-data.json
  packages/commerce-sdk-react/mock-responses/usecustomerorders-returns-error.json
  packages/commerce-sdk-react/mock-responses/usecustomerproductlist-returns-data.json
  packages/commerce-sdk-react/mock-responses/usecustomerproductlist-returns-error.json
  packages/commerce-sdk-react/mock-responses/useorder-returns-data.json
  packages/commerce-sdk-react/mock-responses/useorder-returns-error.json
  packages/commerce-sdk-react/mock-responses/usepaymentmethodsfororder-returns-data.json
  packages/commerce-sdk-react/mock-responses/usepaymentmethodsfororder-returns-error.json
  packages/commerce-sdk-react/mock-responses/useproduct-returns-data.json
  packages/commerce-sdk-react/mock-responses/useproduct-returns-error.json
  packages/commerce-sdk-react/mock-responses/useproducts-returns-data.json
  packages/commerce-sdk-react/mock-responses/useproducts-returns-error.json
  packages/commerce-sdk-react/mock-responses/useproductsearch-returns-data.json
  packages/commerce-sdk-react/mock-responses/useproductsearch-returns-error.json
  packages/commerce-sdk-react/mock-responses/usepromotions-returns-data.json
  packages/commerce-sdk-react/mock-responses/usepromotions-returns-error.json
  packages/commerce-sdk-react/mock-responses/usepromotionsforcampaign-returns-data.json
  packages/commerce-sdk-react/mock-responses/usepromotionsforcampaign-returns-error.json
  packages/commerce-sdk-react/mock-responses/usesearchsuggestions-returns-data.json
  packages/commerce-sdk-react/mock-responses/usesearchsuggestions-returns-error.json
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/mutation.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/query.test.tsx
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/query.ts
  packages/test-commerce-sdk-react/app/pages/home.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-customer.tsx
  packages/test-commerce-sdk-react/app/routes.tsx
Labels: ready for review

#768 [commerce-sdk-react] Implement shopper baskets hooks
  packages/commerce-sdk-react/src/auth/index.test.ts
  packages/commerce-sdk-react/src/auth/index.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/mutation.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/query.ts
  packages/commerce-sdk-react/src/hooks/index.ts
  packages/commerce-sdk-react/src/hooks/useAuthenticatedClient.ts
  packages/commerce-sdk-react/src/hooks/useCustomerId.ts
  packages/commerce-sdk-react/src/hooks/useLocalStorage.ts
  packages/commerce-sdk-react/src/index.ts
  packages/test-commerce-sdk-react/app/components/use-shopper-baskets/use-basket/index.tsx
  packages/test-commerce-sdk-react/app/components/use-shopper-baskets/use-payment-method-for-basket/index.tsx
  packages/test-commerce-sdk-react/app/pages/use-search-suggestions.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-baskets.tsx
  packages/test-commerce-sdk-react/app/routes.tsx
Labels: cla:signed

#790 ApiClient config needs to be updated when cid is changed
  packages/commerce-sdk-react/src/provider.tsx
Labels: ready for review
