Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2022-04, with the labels that each got.

#464 [V2] Service worker loading for dev server
  packages/pwa-kit-build/src/ssr/server/build-dev-server.js
  packages/pwa/app/ssr.js
  packages/pwa/worker/main.js
Labels: ready for review

#490 [V1] Fix rejected 3PP
  packages/pwa-kit-react-sdk/package-lock.json
  packages/pwa-kit-react-sdk/package.json
  packages/pwa-kit-react-sdk/src/ssr/server/express.test.js
  packages/pwa-kit-react-sdk/src/utils/assets.test.js
  packages/pwa-kit-react-sdk/src/utils/ssr-cache.test.js
  packages/pwa-kit-react-sdk/src/utils/ssr-server.test.js
  packages/pwa/app/components/search/index.jsx
  packages/pwa/app/pages/cart/index.jsx
  packages/pwa/package-lock.json
  packages/pwa/package.json
Labels: ready for review

#488 [V2] Fix rejected 3PP
  packages/pwa-kit-react-sdk/package-lock.json
  packages/pwa-kit-react-sdk/package.json
  packages/pwa-kit-react-sdk/src/utils/assets.test.js
  packages/pwa-kit-runtime/package-lock.json
  packages/pwa-kit-runtime/package.json
  packages/pwa-kit-runtime/src/ssr/server/express.test.js
  packages/pwa-kit-runtime/src/utils/ssr-cache.test.js
  packages/pwa-kit-runtime/src/utils/ssr-server.test.js
  packages/pwa/app/components/search/index.jsx
  packages/pwa/app/pages/cart/index.jsx
  packages/pwa/package.json
Labels: ready for review

#491 [V2] Uplift Lighthouse Scores
  packages/pwa/tests/lighthouserc.js
Labels: BUG P3, blocking

#461 [SDK] Fix and rename this build & watch script
  packages/pwa-kit-react-sdk/package.json
Labels: ready for review

#495 [V2]add eslintrc.js to project templates
  packages/pwa/.eslintrc.js
  packages/template-express-minimal/.eslintrc.js
  packages/template-typescript-minimal/.eslintrc.js
Labels: ready for review

#471 [V2] Hide webpack performance warnings
  packages/pwa-kit-build/src/configs/webpack/config.js
  packages/pwa/package.json
Labels: ready for review

#462 [V2] allow custom webpack config in projects
  packages/pwa-kit-build/bin/mrt.js
  packages/pwa-kit-build/src/ssr/server/build-dev-server.js
Labels: ready for review

#492 [V2] Reinstate `pwa-kit-build` Test(s)
  packages/internal-lib-build/configs/jest/setup-jest.js
  packages/internal-lib-build/package.json
  packages/pwa-kit-cli/scripts/upload.test.js
Labels: ready for review, BUG P3, blocking

#508 [V2]Generate different reports for different bundles
  packages/pwa-kit-cli/src/configs/webpack/config.js
  scripts/report-bundle-size.js
Labels: ready for review

#487 [V2] Re-Enable Windows Node 14 CI Workflow
  .circleci/config.yml
  packages/internal-lib-build/bin/internal-lib-build.js
  packages/pwa-kit-cli/bin/cli.js
  packages/template-express-minimal/.eslintignore
  packages/template-express-minimal/package.json
  packages/template-retail-react-app/package.json
  packages/template-typescript-minimal/app/components/hello-typescript.tsx
  packages/template-typescript-minimal/app/main.tsx
  packages/template-typescript-minimal/app/pages/home.tsx
  packages/template-typescript-minimal/app/routes.tsx
  packages/template-typescript-minimal/package.json
Labels: blocking

#522 [V1.5] Webpack config: no longer assumes that `config` dir exists
  packages/pwa-kit-react-sdk/src/webpack/config.js
Labels: ready for review

#532 [V2] Loading page: avoid seeing infinite reloads
  packages/pwa-kit-cli/CHANGELOG.md
  packages/pwa-kit-cli/src/ssr/server/build-dev-server.js
  packages/pwa-kit-cli/src/ssr/server/build-dev-server.test.js
Labels: ready for review

#539 [V2] Fix localization scripts to output to the correct default locale
  packages/template-retail-react-app/package.json
Labels: ready for review

#541 [V2] Replace `aws-lambda-mock-context`
  packages/pwa-kit-runtime/package-lock.json
  packages/pwa-kit-runtime/package.json
  packages/pwa-kit-runtime/src/ssr/server/express.lambda.test.js
Labels: ready for review

#540 [Retail App] When a registered shopper logs in the items in the guest cart should move to the registered cart
  packages/template-retail-react-app/app/commerce-api/auth.js
  packages/template-retail-react-app/app/commerce-api/hooks/useBasket.js
  packages/template-retail-react-app/app/commerce-api/hooks/useCustomer.js
  packages/template-retail-react-app/app/commerce-api/hooks/useShopper.js
  packages/template-retail-react-app/app/commerce-api/index.js
  packages/template-retail-react-app/app/commerce-api/ocapi-shopper-baskets.js
  packages/template-retail-react-app/app/commerce-api/shopper-baskets.js
  packages/template-retail-react-app/app/pages/login/index.test.js
  packages/template-retail-react-app/package-lock.json
  packages/template-retail-react-app/package.json
Labels: ready for review

#553 Deleted ssr server readme file
  packages/pwa-kit-react-sdk/src/ssr/server/README.md
Labels: ready for review

#554 Update develop from release-1.5.x
  package.json
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/pwa-kit-react-sdk/CHANGELOG.md
  packages/pwa-kit-react-sdk/src/webpack/config.js
  packages/pwa/CHANGELOG.md
  packages/pwa/README.md
  packages/pwa/app/commerce-api/auth.js
  packages/pwa/app/commerce-api/index.test.js
  packages/pwa/app/utils/url.js
Labels: ready for review

#533 Add valid token check before using refresh token on login
  packages/template-retail-react-app/app/commerce-api/auth.js
  packages/template-retail-react-app/app/commerce-api/index.test.js
  packages/template-retail-react-app/app/pages/checkout/confirmation.test.js
  packages/template-retail-react-app/app/pages/checkout/index.test.js
Labels: ready for review
