Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2023-03, with the labels that each got.

#1020 Remove unused dependencies.
  packages/commerce-sdk-react/package-lock.json
  packages/commerce-sdk-react/package.json
  packages/commerce-sdk-react/setup-jest.js
  packages/pwa-kit-create-app/package-lock.json
  packages/pwa-kit-create-app/package.json
  packages/pwa-kit-react-sdk/package-lock.json
  packages/pwa-kit-react-sdk/package.json
  packages/pwa-kit-runtime/package-lock.json
  packages/pwa-kit-runtime/package.json
  packages/pwa-kit-runtime/src/utils/ssr-server/outgoing-request-hook.js
  packages/template-express-minimal/package-lock.json
  packages/template-retail-react-app/package-lock.json
  packages/template-retail-react-app/package.json
  packages/template-typescript-minimal/package-lock.json
  packages/template-typescript-minimal/package.json
  packages/test-commerce-sdk-react/package-lock.json
Labels: ready for review

#1040 wishlist integration in pdp and plp
  packages/template-retail-react-app/app/hoc/with-registration/index.jsx
  packages/template-retail-react-app/app/hoc/with-registration/index.test.js
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.test.js
  packages/template-retail-react-app/app/pages/product-list/index.jsx
  packages/template-retail-react-app/app/partials/product-view/index.test.js
Labels: ready for review

#1031 Implement `updateCustomerPassword` as no-op.
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/cache.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/index.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/mutation.test.ts
Labels: ready for review

#1046 Allow query hook parameters to be `null`.
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperContexts/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperContexts/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperExperience/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperExperience/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperGiftCertificates/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperGiftCertificates/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperLogin/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperLogin/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperOrders/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperOrders/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperProducts/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperProducts/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperPromotions/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperPromotions/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperSearch/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperSearch/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/types.ts
  packages/commerce-sdk-react/src/hooks/useQuery.ts
  packages/commerce-sdk-react/src/hooks/utils.ts
Labels: ready for review

#1051 Fix addresses not having preferred address first.
  packages/template-retail-react-app/app/commerce-api/hooks/useCustomer.js
Labels: ready for review

#1048 Make `mergeBasket` Conditional More Robust
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/commerce-api/hooks/useCustomer.js
  packages/template-retail-react-app/app/commerce-api/hooks/useShopper.js
Labels: ready for review

#1039 Hooks integration - My Account Order History
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/app/pages/account/index.test.js
  packages/template-retail-react-app/app/pages/account/order-detail.jsx
  packages/template-retail-react-app/app/pages/account/order-history.jsx
  packages/template-retail-react-app/app/pages/account/orders.jsx
  packages/template-retail-react-app/app/pages/account/orders.test.js
  packages/template-retail-react-app/app/pages/account/util/order-context.js
  packages/template-retail-react-app/app/pages/checkout/index.jsx
  packages/template-retail-react-app/app/translations/compiled/en-US.json
  packages/template-retail-react-app/app/translations/en-US.json
Labels: ready for review

#957 fix(template-retail-react-app): product-list refinements
  packages/template-retail-react-app/app/pages/product-list/index.jsx
  packages/template-retail-react-app/app/pages/product-list/partials/checkbox-refinements.jsx
  packages/template-retail-react-app/app/pages/product-list/partials/color-refinements.jsx
  packages/template-retail-react-app/app/pages/product-list/partials/radio-refinements.jsx
  packages/template-retail-react-app/app/pages/product-list/partials/refinements.jsx
  packages/template-retail-react-app/app/pages/product-list/partials/size-refinements.jsx
Labels: cla:signed, Acknowledged

#1063 Convert shipping options to use hooks
  packages/template-retail-react-app/app/commerce-api/hooks/useBasket.js
  packages/template-retail-react-app/app/pages/checkout/index.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-options.jsx
  packages/template-retail-react-app/app/pages/checkout/util/checkout-context.js
Labels: ready for review

#1071 Update lockfiles to reflect current version.
  package-lock.json
  packages/pwa-kit-dev/package-lock.json
Labels: ready for review

#1069 Fix tests in header and search
  packages/template-retail-react-app/app/components/header/index.test.js
  packages/template-retail-react-app/app/components/search/index.test.js
  packages/template-retail-react-app/app/utils/test-utils.js
Labels: ready for review

#1070 [commerce-sdk-react] Implement remaining Shopper Baskets cache logic
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/cache.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/index.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/mutation.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/mutation.ts
  packages/commerce-sdk-react/src/hooks/types.ts
  packages/commerce-sdk-react/src/hooks/utils.ts
Labels: ready for review

#974 feat(pwa-kit-dev): minor performance improvements and added comments
  packages/pwa-kit-dev/src/configs/webpack/plugins.js
Labels: Acknowledged

#1079 Update dependencies.
  package-lock.json
  package.json
  packages/commerce-sdk-react/package-lock.json
  packages/commerce-sdk-react/package.json
  packages/internal-lib-build/package-lock.json
  packages/internal-lib-build/package.json
  packages/pwa-kit-create-app/package-lock.json
  packages/pwa-kit-create-app/package.json
  packages/pwa-kit-dev/package-lock.json
  packages/pwa-kit-dev/package.json
  packages/pwa-kit-react-sdk/package-lock.json
  packages/pwa-kit-react-sdk/package.json
  packages/pwa-kit-runtime/package-lock.json
  packages/pwa-kit-runtime/package.json
  packages/template-express-minimal/package-lock.json
  packages/template-express-minimal/package.json
  packages/template-mrt-reference-app/package.json
  packages/template-retail-react-app/package-lock.json
  packages/template-retail-react-app/package.json
  packages/template-typescript-minimal/package-lock.json
  packages/template-typescript-minimal/package.json
  packages/test-commerce-sdk-react/package-lock.json
  packages/test-commerce-sdk-react/package.json
  scripts/check-dependencies.js
Labels: ready for review

#1073 Implement Cache Logic for Shopper APIs (Contexts/Customers/Login/Orders)
  packages/commerce-sdk-react/CHANGELOG.md
  packages/commerce-sdk-react/src/components/ShopperExperience/Page/index.tsx
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/cache.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/mutation.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperContexts/cache.ts
  packages/commerce-sdk-react/src/hooks/ShopperContexts/index.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperContexts/mutation.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperContexts/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/cache.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/index.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperExperience/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperGiftCertificates/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperLogin/cache.ts
  packages/commerce-sdk-react/src/hooks/ShopperLogin/index.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperLogin/mutation.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperLogin/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperOrders/cache.ts
  packages/commerce-sdk-react/src/hooks/ShopperOrders/index.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperOrders/mutation.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperOrders/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperProducts/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperPromotions/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperSearch/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/types.ts
  packages/commerce-sdk-react/src/hooks/useAuthHelper.ts
  packages/commerce-sdk-react/src/test-utils.tsx
  packages/test-commerce-sdk-react/app/components/Json.tsx
  packages/test-commerce-sdk-react/app/pages/home.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-context.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-customer.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-orders.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-products.tsx
  packages/test-commerce-sdk-react/app/routes.tsx
Labels: ready for review

#1089 Replace wishlist with hook in the rest of the codebase
  packages/template-retail-react-app/app/components/_app/index.jsx
  packages/template-retail-react-app/app/components/recommended-products/index.jsx
  packages/template-retail-react-app/app/hooks/use-wish-list.js
  packages/template-retail-react-app/app/hooks/use-wishlist.js
  packages/template-retail-react-app/app/hooks/use-wishlist.test.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/app/pages/product-list/index.test.js
Labels: ready for review

#1088 Move asset out of commerce api folder
  packages/template-retail-react-app/app/commerce-api/index.test.js
  packages/template-retail-react-app/app/commerce-api/ocapi-shopper-baskets.test.js
  packages/template-retail-react-app/app/commerce-api/ocapi-shopper-orders.test.js
  packages/template-retail-react-app/app/components/header/index.test.js
  packages/template-retail-react-app/app/components/product-item/index.test.js
  packages/template-retail-react-app/app/components/product-view-modal/index.test.js
  packages/template-retail-react-app/app/components/search/index.test.js
  packages/template-retail-react-app/app/hoc/with-registration/index.test.js
  packages/template-retail-react-app/app/hooks/use-add-to-cart-modal.test.js
  packages/template-retail-react-app/app/hooks/use-auth-modal.test.js
  packages/template-retail-react-app/app/hooks/use-categories.test.js
  packages/template-retail-react-app/app/hooks/use-derived-product.test.js
  packages/template-retail-react-app/app/hooks/use-product-view-modal.test.js
  packages/template-retail-react-app/app/mocks/basket-with-suit.js
  packages/template-retail-react-app/app/mocks/empty-basket.js
  packages/template-retail-react-app/app/mocks/mock-data.js
  packages/template-retail-react-app/app/mocks/product-set-winter-lookM.js
  packages/template-retail-react-app/app/mocks/searchResults.js
  packages/template-retail-react-app/app/mocks/variant-750518699578M.js
  packages/template-retail-react-app/app/pages/account/addresses.test.js
  packages/template-retail-react-app/app/pages/account/index.test.js
  packages/template-retail-react-app/app/pages/account/orders.test.js
  packages/template-retail-react-app/app/pages/cart/index.test.js
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.test.js
  packages/template-retail-react-app/app/pages/checkout/index.test.js
  packages/template-retail-react-app/app/pages/login/index.test.js
  packages/template-retail-react-app/app/pages/product-detail/index.test.js
  packages/template-retail-react-app/app/pages/product-list/index.test.js
  packages/template-retail-react-app/app/pages/registration/index.test.jsx
  packages/template-retail-react-app/app/partials/product-view/index.test.js
  packages/template-retail-react-app/app/utils/test-utils.js
  packages/template-retail-react-app/jest-setup.js
Labels: ready for review

#1096 Fix einstein loading state
  packages/template-retail-react-app/app/components/recommended-products/index.jsx
  packages/template-retail-react-app/app/hooks/use-einstein.js
Labels: ready for review

#1087 Remove category provider
  packages/template-retail-react-app/app/components/_app-config/index.test.js
  packages/template-retail-react-app/app/components/_app/index.jsx
  packages/template-retail-react-app/app/components/drawer-menu/index.jsx
  packages/template-retail-react-app/app/components/drawer-menu/index.test.js
  packages/template-retail-react-app/app/components/list-menu/index.jsx
  packages/template-retail-react-app/app/components/list-menu/index.test.js
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/app/contexts/index.js
  packages/template-retail-react-app/app/hooks/use-categories.js
  packages/template-retail-react-app/app/hooks/use-categories.test.js
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.test.js
  packages/template-retail-react-app/app/pages/product-list/index.test.js
  packages/template-retail-react-app/app/pages/product-list/partials/checkbox-refinements.test.js
  packages/template-retail-react-app/app/utils/test-utils.js
  packages/template-retail-react-app/app/utils/utils.js
  packages/template-retail-react-app/jest-setup.js
  packages/template-retail-react-app/jest.config.js
Labels: ready for review
