Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2023-01, with the labels that each got.

#876 New year, new look!
  .circleci/config.yml
  .eslintrc.js
  LICENSE
Labels: ready for review

#899 Change padding
  packages/template-retail-react-app/app/theme/components/base/drawer.js
Labels: cla:signed

#880 [Commerce SDK React Integration] Product List Page
  packages/commerce-sdk-react/package-lock.json
  packages/pwa-kit-create-app/package-lock.json
  packages/pwa-kit-runtime/package-lock.json
  packages/template-express-minimal/package-lock.json
  packages/template-retail-react-app/app/commerce-api/mock-data.js
  packages/template-retail-react-app/app/components/_app-config/index.jsx
  packages/template-retail-react-app/app/components/header/index.test.js
  packages/template-retail-react-app/app/components/search/index.test.js
  packages/template-retail-react-app/app/hoc/with-registration/index.test.js
  packages/template-retail-react-app/app/hooks/use-product-view-modal.test.js
  packages/template-retail-react-app/app/hooks/use-search-params.js
  packages/template-retail-react-app/app/hooks/use-search-params.test.js
  packages/template-retail-react-app/app/pages/account/addresses.test.js
  packages/template-retail-react-app/app/pages/account/index.test.js
  packages/template-retail-react-app/app/pages/account/orders.test.js
  packages/template-retail-react-app/app/pages/account/payments.test.js
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.test.js
  packages/template-retail-react-app/app/pages/checkout/confirmation.test.js
  packages/template-retail-react-app/app/pages/checkout/index.test.js
  packages/template-retail-react-app/app/pages/login/index.test.js
  packages/template-retail-react-app/app/pages/product-detail/index.test.js
  packages/template-retail-react-app/app/pages/product-list/index.jsx
  packages/template-retail-react-app/app/pages/product-list/index.test.js
  packages/template-retail-react-app/app/pages/product-list/partials/selected-refinements.jsx
  packages/template-retail-react-app/app/pages/product-list/partials/size-refinements.jsx
  packages/template-retail-react-app/app/pages/reset-password/index.test.jsx
  packages/template-retail-react-app/app/partials/product-view/index.test.js
  packages/template-retail-react-app/app/utils/test-utils.js
  packages/template-retail-react-app/config/mocks/default.js
  packages/template-retail-react-app/jest-setup.js
  packages/template-retail-react-app/jest.config.js
  packages/template-retail-react-app/package-lock.json
  packages/template-retail-react-app/package.json
  packages/template-typescript-minimal/package-lock.json
  packages/test-commerce-sdk-react/package-lock.json
Labels: cla:signed

#852 [Snyk] Security upgrade express from 4.17.1 to 4.17.3
  packages/hello-world/package-lock.json
  packages/hello-world/package.json
Labels: cla:signed

#853 [Snyk] Security upgrade express from 4.17.1 to 4.17.3
  CODE_OF_CONDUCT.md
  packages/pwa/package-lock.json
  packages/pwa/package.json
Labels: cla:signed, USER STORY

#930 Backport GitHub Actions to v1
  .circleci/config.yml
  .github/actions/check_clean/action.yml
  .github/actions/count_deps/action.yml
  .github/actions/datadog/action.yml
  .github/actions/lighthouse_ci/action.yml
  .github/actions/publish_to_npm/action.yml
  .github/actions/setup_ubuntu/action.yml
  .github/actions/setup_windows/action.yml
  .github/actions/smoke_tests/action.yml
  .github/actions/snyk/action.yml
  .github/actions/unit_tests/action.yml
  .github/workflows/test.yml
  CODE_OF_CONDUCT.md
  lerna.json
  package.json
  packages/hello-world/package-lock.json
  packages/hello-world/package.json
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/pwa-kit-create-app/package-lock.json
  packages/pwa-kit-create-app/package.json
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
  packages/pwa-kit-react-sdk/CHANGELOG.md
  packages/pwa-kit-react-sdk/README.md
  packages/pwa-kit-react-sdk/package-lock.json
  packages/pwa-kit-react-sdk/package.json
  packages/pwa/CHANGELOG.md
  packages/pwa/app/commerce-api/mock-data.js
  packages/pwa/app/pages/account/payments.test.js
  packages/pwa/app/pages/checkout/index.test.js
  packages/pwa/package-lock.json
  packages/pwa/package.json
Labels: cla:signed

#911 Allow support for multiple sites concurrently w/ `commerce-sdk-react`
  packages/commerce-sdk-react/CHANGELOG.md
  packages/commerce-sdk-react/src/auth/index.test.ts
  packages/commerce-sdk-react/src/auth/index.ts
  packages/commerce-sdk-react/src/auth/storage.test.ts
  packages/commerce-sdk-react/src/auth/storage.ts
  packages/commerce-sdk-react/src/utils.ts
Labels: ready for review

#942 fix: handle special characters in `boldString` util
  packages/template-retail-react-app/app/utils/utils.js
  packages/template-retail-react-app/app/utils/utils.test.js
Labels: cla:signed

#945 Update customer baskets cache when there is a basket mutation
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/mutation.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/mutation.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/mutation.test.tsx
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/mutation.ts
  packages/commerce-sdk-react/src/hooks/ShopperOrders/mutation.ts
  packages/commerce-sdk-react/src/hooks/utils.ts
  packages/commerce-sdk-react/src/test-utils.tsx
Labels: ready for review
