Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2023-04, with the labels that each got.

#1105 remove commerce api folder
  packages/template-retail-react-app/app/commerce-api/auth.js
  packages/template-retail-react-app/app/commerce-api/contexts.js
  packages/template-retail-react-app/app/commerce-api/hooks/useBasket.js
  packages/template-retail-react-app/app/commerce-api/hooks/useCustomer.js
  packages/template-retail-react-app/app/commerce-api/hooks/useCustomerProductList.js
  packages/template-retail-react-app/app/commerce-api/hooks/useCustomerProductLists.js
  packages/template-retail-react-app/app/commerce-api/hooks/useRefinementToggle.js
  packages/template-retail-react-app/app/commerce-api/hooks/useShopper.js
  packages/template-retail-react-app/app/commerce-api/index.js
  packages/template-retail-react-app/app/commerce-api/index.test.js
  packages/template-retail-react-app/app/commerce-api/ocapi-shopper-baskets.js
  packages/template-retail-react-app/app/commerce-api/ocapi-shopper-baskets.test.js
  packages/template-retail-react-app/app/commerce-api/ocapi-shopper-orders.js
  packages/template-retail-react-app/app/commerce-api/ocapi-shopper-orders.test.js
  packages/template-retail-react-app/app/commerce-api/pkce.js
  packages/template-retail-react-app/app/commerce-api/shopper-baskets.js
  packages/template-retail-react-app/app/commerce-api/utils.js
  packages/template-retail-react-app/app/commerce-api/utils.test.js
  packages/template-retail-react-app/app/components/_app-config/index.jsx
  packages/template-retail-react-app/app/components/_app-config/index.test.js
  packages/template-retail-react-app/app/components/_app/index.jsx
  packages/template-retail-react-app/app/mocks/mock-data.js
  packages/template-retail-react-app/app/utils/test-utils.js
  packages/template-retail-react-app/jest-setup.js
  packages/template-retail-react-app/jest.config.js
  packages/template-retail-react-app/package-lock.json
  packages/template-retail-react-app/package.json
Labels: ready for review

#1107 add locale and currency to apiClients
  packages/commerce-sdk-react/src/hooks/types.ts
  packages/commerce-sdk-react/src/provider.tsx
  packages/template-retail-react-app/app/components/_app/index.jsx
Labels: ready for review

#1092 Fix Page Designer ImageWithText Link component
  packages/template-retail-react-app/app/page-designer/assets/image-with-text/index.jsx
  packages/template-retail-react-app/app/page-designer/utils.js
Labels: ready for review

#1115 Sort contents of package.json files.
  package.json
  packages/commerce-sdk-react/package.json
  packages/internal-lib-build/package.json
  packages/pwa-kit-create-app/package.json
  packages/pwa-kit-dev/package.json
  packages/pwa-kit-react-sdk/package.json
  packages/pwa-kit-runtime/package.json
  packages/template-express-minimal/package.json
  packages/template-mrt-reference-app/package.json
  packages/template-retail-react-app/package.json
  packages/template-typescript-minimal/package.json
  packages/test-commerce-sdk-react/package.json
Labels: ready for review

#1119 dont use callback on mutateAsync
  packages/template-retail-react-app/app/pages/login/index.jsx
  packages/template-retail-react-app/app/pages/registration/index.jsx
Labels: ready for review

#1114 Add mergeBasket hook
  packages/template-retail-react-app/app/hooks/use-auth-modal.js
  packages/template-retail-react-app/app/hooks/use-previous.js
  packages/template-retail-react-app/app/pages/login/index.jsx
Labels: ready for review

#1100 Upgrade msw to latest
  packages/template-retail-react-app/app/components/_app-config/index.test.js
  packages/template-retail-react-app/app/pages/cart/index.test.js
  packages/template-retail-react-app/app/pages/checkout/confirmation.mock.js
  packages/template-retail-react-app/app/pages/checkout/confirmation.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-address-selection.jsx
  packages/template-retail-react-app/jest-setup.js
  packages/template-retail-react-app/package-lock.json
  packages/template-retail-react-app/package.json
Labels: ready for review

#1123 Increase test timeouts only on CI env
  packages/template-retail-react-app/jest-setup.js
  packages/template-retail-react-app/jest.config.js
Labels: ready for review

#1127 CI: clarify the environment variables
  .github/workflows/test.yml
Labels: ready for review

#1148 Merge `develop` into `v3`
  packages/template-retail-react-app/app/page-designer/assets/image-with-text/index.jsx
  packages/template-retail-react-app/app/page-designer/utils.js
Labels: cla:missing

#1146 [Spike]Replace watch with nodemon
  packages/commerce-sdk-react/package-lock.json
  packages/commerce-sdk-react/package.json
  packages/pwa-kit-dev/package-lock.json
  packages/pwa-kit-dev/package.json
  packages/pwa-kit-react-sdk/package-lock.json
  packages/pwa-kit-react-sdk/package.json
  packages/pwa-kit-runtime/package-lock.json
  packages/pwa-kit-runtime/package.json
Labels: ready for review, cla:signed
