Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2024-08, with the labels that each got.

#1948 [Release process] Changelog files are updated (@W-16164410@)
  .github/actions/changelog-check/action.yml
  .github/workflows/test.yml
Labels: ready for review, open for visibility

#1966 Drop unused njwt dependency @W-16386042@
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/package-lock.json
  packages/template-retail-react-app/package.json
Labels: skip changelog

#1962 [Release process] Fix Changelog check on base branch (@W-16164410@)
  .github/actions/changelog-check/action.yml
Labels: ready for review
