Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2025-06, with the labels that each got.

#2504 [Chakra V3 Upgrade 🎨] Update QuantityPicker Component @@W-18682956@@
  packages/extension-chakra-storefront/jest.config.js
  packages/extension-chakra-storefront/src/components/quantity-picker/index.jsx
  packages/extension-chakra-storefront/src/components/quantity-picker/index.test.js
  packages/extension-chakra-storefront/src/components/quantity-picker/index.test.jsx
  packages/extension-chakra-storefront/src/setup-app.tsx
  packages/extension-chakra-storefront/src/theme/components/project/quantity-picker.js
  packages/extension-chakra-storefront/src/theme/index.js
Labels: skip changelog

#2512 [Chakra V3 Upgrade 🎨] Update NestedAccordion Component @@W-18687117@@
  packages/extension-chakra-storefront/jest.config.js
  packages/extension-chakra-storefront/src/components/nested-accordion/index.jsx
  packages/extension-chakra-storefront/src/components/nested-accordion/index.test.js
  packages/extension-chakra-storefront/src/pages/product-detail/partials/information-accordion.jsx
  packages/extension-chakra-storefront/src/setup-app.tsx
  packages/extension-chakra-storefront/src/theme/components/project/nested-accordion.js
  packages/extension-chakra-storefront/src/theme/index.js
Labels: skip changelog

#2505 [Chakra V3 Upgrade 🎨] Update checkout skeleton Component @@W-18685099@@
  packages/extension-chakra-storefront/src/components/with-layout/with-layout.tsx
  packages/extension-chakra-storefront/src/pages/checkout/index.jsx
  packages/extension-chakra-storefront/src/pages/checkout/partials/checkout-skeleton.jsx
  packages/extension-chakra-storefront/src/pages/index.tsx
  packages/extension-chakra-storefront/src/setup-app.tsx
Labels: skip changelog

#2506 `commerce-sdk-react` is also compatible with older React 17 (@W-18568155@)
  package.json
  packages/commerce-sdk-react/CHANGELOG.md
  packages/commerce-sdk-react/package-lock.json
  packages/commerce-sdk-react/package.json
  packages/commerce-sdk-react/src/hooks/useLocalStorage.test.ts
  packages/commerce-sdk-react/src/hooks/useLocalStorage.ts
  packages/pwa-kit-runtime/package-lock.json
Labels: skip changelog

#2523 [Chakra V3 Upgrade 🎨] Update useAddToCartModal Component @@W-18718985@@
  packages/extension-chakra-storefront/src/components/product-view/index.jsx
  packages/extension-chakra-storefront/src/components/with-registration/index.jsx
  packages/extension-chakra-storefront/src/hooks/use-add-to-cart-modal.js
  packages/extension-chakra-storefront/src/hooks/use-einstein.js
  packages/extension-chakra-storefront/src/setup-app.tsx
Labels: skip changelog

#2517 [Chakra V3 Upgrade 🎨] Update Product Detail Page @@W-18394804@@
  packages/extension-chakra-storefront/jest.config.js
  packages/extension-chakra-storefront/src/components/fade/index.jsx
  packages/extension-chakra-storefront/src/components/fade/index.test.js
  packages/extension-chakra-storefront/src/components/image-gallery/index.jsx
  packages/extension-chakra-storefront/src/components/product-view/index.jsx
  packages/extension-chakra-storefront/src/components/quantity-picker/index.jsx
  packages/extension-chakra-storefront/src/components/with-layout/with-layout.tsx
  packages/extension-chakra-storefront/src/pages/index.tsx
  packages/extension-chakra-storefront/src/pages/product-detail/index.jsx
  packages/extension-chakra-storefront/src/pages/product-detail/partials/information-accordion.jsx
  packages/extension-chakra-storefront/src/setup-app.tsx
  packages/extension-chakra-storefront/src/theme/components/project/image-gallery.js
  packages/extension-chakra-storefront/src/utils/test-utils.js
Labels: skip changelog

#2508 @W-18698228 - Add Unit Test Coverage to PLP
  packages/template-retail-react-app/app/pages/product-list/index.test.js
Labels: ready for review, skip changelog

#2529 @W-18725883 feat: unit test coverage for pagination
  packages/template-retail-react-app/app/components/pagination/index.test.js
Labels: skip changelog

#2545 @W-18698408 : Removed unneeded hyphen as part of onboarding.
  packages/template-retail-react-app/app/components/locale-text/index.jsx
Labels: ready for review, skip changelog

#2542 Migrate store locator from feature branch to develop
  packages/template-retail-react-app/app/components/_app-config/index.jsx
  packages/template-retail-react-app/app/components/_app/index.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/index.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/index.test.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/store-locator-content.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/store-locator-content.test.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/store-locator-input.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/store-locator-input.test.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/stores-list.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/stores-list.test.jsx
  packages/template-retail-react-app/app/components/store-locator/diagram.png
  packages/template-retail-react-app/app/components/store-locator/form.jsx
  packages/template-retail-react-app/app/components/store-locator/form.test.jsx
  packages/template-retail-react-app/app/components/store-locator/heading.jsx
  packages/template-retail-react-app/app/components/store-locator/heading.test.jsx
  packages/template-retail-react-app/app/components/store-locator/index.js
  packages/template-retail-react-app/app/components/store-locator/list-item.jsx
  packages/template-retail-react-app/app/components/store-locator/list-item.test.jsx
  packages/template-retail-react-app/app/components/store-locator/list.jsx
  packages/template-retail-react-app/app/components/store-locator/list.test.jsx
  packages/template-retail-react-app/app/components/store-locator/main.jsx
  packages/template-retail-react-app/app/components/store-locator/main.test.jsx
  packages/template-retail-react-app/app/components/store-locator/modal.jsx
  packages/template-retail-react-app/app/components/store-locator/modal.test.jsx
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/app/contexts/index.js
  packages/template-retail-react-app/app/contexts/store-locator-provider.jsx
  packages/template-retail-react-app/app/contexts/store-locator-provider.test.jsx
  packages/template-retail-react-app/app/hooks/use-geo-location.js
  packages/template-retail-react-app/app/hooks/use-geo-location.test.js
  packages/template-retail-react-app/app/hooks/use-store-locator.js
  packages/template-retail-react-app/app/hooks/use-store-locator.test.jsx
  packages/template-retail-react-app/app/pages/store-locator/index.jsx
  packages/template-retail-react-app/app/pages/store-locator/index.test.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/app/utils/test-utils.js
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2552 Update existing translations with updated localization
  packages/template-retail-react-app/app/static/translations/compiled/de-DE.json
  packages/template-retail-react-app/app/static/translations/compiled/es-MX.json
  packages/template-retail-react-app/app/static/translations/compiled/fr-FR.json
  packages/template-retail-react-app/app/static/translations/compiled/it-IT.json
  packages/template-retail-react-app/app/static/translations/compiled/ja-JP.json
  packages/template-retail-react-app/app/static/translations/compiled/ko-KR.json
  packages/template-retail-react-app/app/static/translations/compiled/pt-BR.json
  packages/template-retail-react-app/app/static/translations/compiled/zh-CN.json
  packages/template-retail-react-app/app/static/translations/compiled/zh-TW.json
  packages/template-retail-react-app/translations/de-DE.json
  packages/template-retail-react-app/translations/es-MX.json
  packages/template-retail-react-app/translations/fr-FR.json
  packages/template-retail-react-app/translations/it-IT.json
  packages/template-retail-react-app/translations/ja-JP.json
  packages/template-retail-react-app/translations/ko-KR.json
  packages/template-retail-react-app/translations/pt-BR.json
  packages/template-retail-react-app/translations/zh-CN.json
  packages/template-retail-react-app/translations/zh-TW.json
Labels: skip changelog

#2562 @W-18597966 - Add Bonus Product Label
  packages/template-retail-react-app/app/components/item-variant/item-attributes.jsx
  packages/template-retail-react-app/app/components/item-variant/item-attributes.test.js
  packages/template-retail-react-app/app/components/product-item/index.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: ready for review, skip changelog

#2572 @W-18407625: Fix small label issue with quantity
  packages/template-retail-react-app/app/components/product-item/bonus-product-quantity.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: ready for review, skip changelog

#2549 [Chakra V3 Upgrade 🎨] Update listMenu Component @@W-18507835@@
  packages/extension-chakra-storefront/jest.config.js
  packages/extension-chakra-storefront/src/components/list-menu/list-menu-content.jsx
  packages/extension-chakra-storefront/src/components/list-menu/list-menu-popover.jsx
  packages/extension-chakra-storefront/src/components/list-menu/list-menu-trigger.jsx
  packages/extension-chakra-storefront/src/components/list-menu/list-menu.jsx
  packages/extension-chakra-storefront/src/components/with-layout/with-layout.tsx
  packages/extension-chakra-storefront/src/theme/components/project/list-menu.js
  packages/extension-chakra-storefront/src/theme/index.js
Labels: skip changelog

#2590 @W-18785684: configuring contextual variables ( IsCartMgmtSupported )
  packages/pwa-kit-dev/src/ssr/server/public-path.js
  packages/pwa-kit-runtime/src/utils/ssr-server.test.js
  packages/template-retail-react-app/app/components/reset-password/index.test.js
  packages/template-retail-react-app/app/components/shopper-agent/index.jsx
  packages/template-retail-react-app/app/components/shopper-agent/index.test.js
Labels: skip changelog

#2576 @W-18762161 BOPIS add to cart for store pick up
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.test.js
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.test.js
Labels: skip changelog

#2611 @W-18838421 skip changelog Enable Passwordless login for One click checkout POC
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/components/_app-config/index.jsx
  packages/template-retail-react-app/app/ssr.js
  packages/template-retail-react-app/config/default.js
  packages/template-typescript-minimal/package.json
  packages/test-commerce-sdk-react/app/components/_app-config/index.tsx
  packages/test-commerce-sdk-react/package.json
Labels: skip changelog

#2609 @W-18670798 BOPIS show store on order confirmation page
  packages/template-retail-react-app/app/components/product-view-modal/bundle.test.js
  packages/template-retail-react-app/app/components/store-display/index.jsx
  packages/template-retail-react-app/app/components/store-display/index.test.js
  packages/template-retail-react-app/app/pages/checkout/confirmation.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2584 @W-18762060 feat: new store locator into feature branch and restore store selection functionality
  packages/template-retail-react-app/app/components/_app-config/index.jsx
  packages/template-retail-react-app/app/components/_app/index.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/index.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/index.test.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/store-locator-content.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/store-locator-content.test.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/store-locator-input.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/store-locator-input.test.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/stores-list.jsx
  packages/template-retail-react-app/app/components/store-locator-modal/stores-list.test.jsx
  packages/template-retail-react-app/app/components/store-locator/diagram.png
  packages/template-retail-react-app/app/components/store-locator/form.jsx
  packages/template-retail-react-app/app/components/store-locator/form.test.jsx
  packages/template-retail-react-app/app/components/store-locator/heading.jsx
  packages/template-retail-react-app/app/components/store-locator/heading.test.jsx
  packages/template-retail-react-app/app/components/store-locator/index.js
  packages/template-retail-react-app/app/components/store-locator/list-item.jsx
  packages/template-retail-react-app/app/components/store-locator/list-item.test.jsx
  packages/template-retail-react-app/app/components/store-locator/list.jsx
  packages/template-retail-react-app/app/components/store-locator/list.test.jsx
  packages/template-retail-react-app/app/components/store-locator/main.jsx
  packages/template-retail-react-app/app/components/store-locator/main.test.jsx
  packages/template-retail-react-app/app/components/store-locator/modal.jsx
  packages/template-retail-react-app/app/components/store-locator/modal.test.jsx
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/app/contexts/index.js
  packages/template-retail-react-app/app/contexts/store-locator-provider.jsx
  packages/template-retail-react-app/app/contexts/store-locator-provider.test.jsx
  packages/template-retail-react-app/app/hooks/use-geo-location.js
  packages/template-retail-react-app/app/hooks/use-geo-location.test.js
  packages/template-retail-react-app/app/hooks/use-se-store-selection.js
  packages/template-retail-react-app/app/hooks/use-se-store-selection.test.js
  packages/template-retail-react-app/app/hooks/use-store-locator.js
  packages/template-retail-react-app/app/hooks/use-store-locator.test.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.test.js
  packages/template-retail-react-app/app/pages/product-list/partials/inventory-filter.jsx
  packages/template-retail-react-app/app/pages/product-list/partials/inventory-filter.test.js
  packages/template-retail-react-app/app/pages/store-locator/index.jsx
  packages/template-retail-react-app/app/pages/store-locator/index.test.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/app/utils/test-utils.js
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2566 @W-18668857 - Display bonus product name and image in the modal when there are bonus products in AddToCart response
  packages/template-retail-react-app/app/components/bonus-product-modal/index.jsx
  packages/template-retail-react-app/app/components/bonus-product-modal/index.test.jsx
  packages/template-retail-react-app/app/hooks/use-bonus-product-modal.js
  packages/template-retail-react-app/app/hooks/use-bonus-product-modal.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/package.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: ready for review, skip changelog

#2581 @W-12360935 Modify the Product Card to support standard products
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.jsx
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.test.js
Labels: ready for review

#2633 Merge develop into standard-product-support
  packages/template-retail-react-app/app/components/product-view-modal/bundle.test.js
Labels: skip changelog

#2619 Revert "@W-18795492 | PWA Kit - Adyen ApplePay in Cart (#2571)"
  packages/template-retail-react-app/app/components/_app/index.jsx
  packages/template-retail-react-app/app/components/applePayExpress/index.jsx
  packages/template-retail-react-app/app/components/applePayExpress/index.test.jsx
  packages/template-retail-react-app/app/components/applePayExpress/utils/api.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/api.test.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/currencyList.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/currencyList.test.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/parsers.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/parsers.test.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/payments.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/payments.test.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/shipping-address.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/shipping-address.test.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/shipping-methods.js
  packages/template-retail-react-app/app/components/applePayExpress/utils/shipping-methods.test.js
  packages/template-retail-react-app/app/components/express/index.jsx
  packages/template-retail-react-app/app/components/shopper-agent/index.jsx
  packages/template-retail-react-app/app/pages/checkout/error/index.jsx
  packages/template-retail-react-app/app/pages/checkout/redirect/index.jsx
  packages/template-retail-react-app/app/pages/checkout/redirect/index.test.jsx
  packages/template-retail-react-app/app/pages/express/index.jsx
  packages/template-retail-react-app/app/routes.jsx
  packages/template-retail-react-app/app/ssr.js
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/app/styles/adyen-overrides.css
  packages/template-retail-react-app/package-lock.json
  packages/template-retail-react-app/package.json
  packages/template-retail-react-app/webpack.config.js
Labels: skip changelog

#2647 @W-18891885 - Handle Store Change on PLP
  packages/template-retail-react-app/app/pages/product-list/partials/inventory-filter.jsx
  packages/template-retail-react-app/app/pages/product-list/partials/inventory-filter.test.js
Labels: skip changelog

#2603 W-18672731 Chakra v3 cart page
  packages/extension-chakra-storefront/jest.config.js
  packages/extension-chakra-storefront/package.json
  packages/extension-chakra-storefront/src/components/confirmation-modal/index.jsx
  packages/extension-chakra-storefront/src/components/fade/index.test.js
  packages/extension-chakra-storefront/src/components/field/index.jsx
  packages/extension-chakra-storefront/src/components/forms/login-fields.jsx
  packages/extension-chakra-storefront/src/components/forms/promo-code-fields.jsx
  packages/extension-chakra-storefront/src/components/header/index.jsx
  packages/extension-chakra-storefront/src/components/hero/index.test.js
  packages/extension-chakra-storefront/src/components/icons/index.test.js
  packages/extension-chakra-storefront/src/components/image-gallery/index.jsx
  packages/extension-chakra-storefront/src/components/item-variant/item-attributes.jsx
  packages/extension-chakra-storefront/src/components/item-variant/item-price.jsx
  packages/extension-chakra-storefront/src/components/list-menu/list-menu-trigger.jsx
  packages/extension-chakra-storefront/src/components/list-menu/list-menu.test.js
  packages/extension-chakra-storefront/src/components/login/index.test.js
  packages/extension-chakra-storefront/src/components/order-summary/index.jsx
  packages/extension-chakra-storefront/src/components/pagination/index.jsx
  packages/extension-chakra-storefront/src/components/pagination/index.test.js
  packages/extension-chakra-storefront/src/components/product-item/index.jsx
  packages/extension-chakra-storefront/src/components/product-scroller/index.test.js
  packages/extension-chakra-storefront/src/components/product-tile/index.test.js
  packages/extension-chakra-storefront/src/components/product-view-modal/index.jsx
  packages/extension-chakra-storefront/src/components/product-view/index.test.js
  packages/extension-chakra-storefront/src/components/promo-code/index.jsx
  packages/extension-chakra-storefront/src/components/promo-popover/index.jsx
  packages/extension-chakra-storefront/src/components/promo-popover/index.test.js
  packages/extension-chakra-storefront/src/components/quantity-picker/index.test.js
  packages/extension-chakra-storefront/src/components/reset-password/index.test.js
  packages/extension-chakra-storefront/src/components/search/index.test.js
  packages/extension-chakra-storefront/src/components/social-icons/index.test.js
  packages/extension-chakra-storefront/src/components/standard-login/index.jsx
  packages/extension-chakra-storefront/src/components/toaster/index.test.jsx
  packages/extension-chakra-storefront/src/components/with-registration/index.test.js
  packages/extension-chakra-storefront/src/hooks/use-add-to-cart-modal.js
  packages/extension-chakra-storefront/src/pages/cart/index.jsx
  packages/extension-chakra-storefront/src/pages/cart/index.test.js
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-cta.jsx
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-secondary-button-group.jsx
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-secondary-button-group.test.js
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-skeleton.jsx
  packages/extension-chakra-storefront/src/pages/cart/partials/empty-cart.jsx
  packages/extension-chakra-storefront/src/pages/home/index.test.js
  packages/extension-chakra-storefront/src/pages/index.tsx
  packages/extension-chakra-storefront/src/pages/product-list/index.jsx
  packages/extension-chakra-storefront/src/pages/product-list/index.test.js
  packages/extension-chakra-storefront/src/setup-app.tsx
  packages/extension-chakra-storefront/src/theme/components/base/button.js
  packages/extension-chakra-storefront/src/theme/components/base/input.js
  packages/extension-chakra-storefront/src/theme/components/base/modal.js
  packages/extension-chakra-storefront/src/theme/components/project/search.js
  packages/extension-chakra-storefront/src/theme/foundations/layerStyles.js
  packages/extension-chakra-storefront/src/utils/site-utils.js
Labels: ready for review

#2652 @W-18779257 BOPIS format store hours on confirmation
  packages/template-retail-react-app/app/components/store-display/index.jsx
  packages/template-retail-react-app/app/hooks/use-store-locator.js
Labels: skip changelog

#2569 @W 18598170 - Add Select Bonus Products Button on Cart Page
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/cart/partials/bonus-products-title.jsx
  packages/template-retail-react-app/app/pages/cart/partials/bonus-products-title.test.js
  packages/template-retail-react-app/app/pages/cart/partials/cart-select-bonus-button.jsx
  packages/template-retail-react-app/app/pages/cart/partials/cart-select-bonus-button.test.js
Labels: ready for review, skip changelog

#2667 @W-18902458 Multi-Site store query issue fix
  packages/template-retail-react-app/app/hooks/use-external-search.js
  packages/template-retail-react-app/app/hooks/use-external-search.test.js
Labels: skip changelog

#2649 @W-12360935 2nd PR- fixing Edit button appearing briefly for standard products
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.jsx
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.test.js
Labels: ready for review, skip changelog

#2673 @W-18902385 - [BOPIS][Bug] Fix prefilling shipping address bug
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-address.jsx
  packages/template-retail-react-app/app/pages/checkout/util/checkout-context.js
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
Labels: skip changelog

#2679 @W-18902403 - Select Off of Pickup in Store Option on PDP if New Store is Out of Stock
  packages/template-retail-react-app/app/components/product-view/index.jsx
  packages/template-retail-react-app/app/components/product-view/index.test.js
Labels: skip changelog

#2674 @W-18903896 do not trigger bonus modal for rule based promotions - MVP
  packages/template-retail-react-app/app/components/product-view/index.jsx
  packages/template-retail-react-app/app/components/product-view/index.test.js
Labels: ready for review, skip changelog

#2687 @W-18902360 @W-18902533 BOPIS less content switch with store selection
  packages/template-retail-react-app/app/components/store-locator/form.jsx
  packages/template-retail-react-app/app/components/store-locator/list.jsx
  packages/template-retail-react-app/app/contexts/store-locator-provider.jsx
  packages/template-retail-react-app/app/contexts/store-locator-provider.test.jsx
  packages/template-retail-react-app/app/hooks/use-store-locator.js
  packages/template-retail-react-app/app/hooks/use-store-locator.test.jsx
Labels: skip changelog

#2682 Cleanup from Select bonus button PR
  packages/template-retail-react-app/app/components/product-view/index.jsx
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/cart/partials/cart-bonus-products.jsx
  packages/template-retail-react-app/app/pages/cart/partials/cart-bonus-products.test.js
  packages/template-retail-react-app/app/pages/cart/partials/cart-select-bonus-button.jsx
  packages/template-retail-react-app/app/pages/cart/partials/cart-select-bonus-button.test.js
Labels: ready for review, skip changelog

#2688 @W-18670301 - added prettier and improved tests for trim-extensions script
  package-lock.json
  package.json
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/pwa-kit-create-app/scripts/trim-extensions.js
  packages/pwa-kit-create-app/scripts/trim-extensions.test.js
Labels: skip changelog

#2638 @W-18831461 Unit test using cursor rules
  packages/template-retail-react-app/app/components/drawer-menu/drawer-menu.test.js
  packages/template-retail-react-app/app/components/header/index.test.js
Labels: skip changelog

#2640 @W-18587861@ - Add documentation for transformSDKClient to commerce-sdk-react README
  packages/commerce-sdk-react/README.md
Labels: skip changelog

#2681 @W-18902413 - Fixed Incorrect Add to Cart Error
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.js
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.test.js
Labels: skip changelog

#2694 @W-18902257 - [BOPIS] Implement feature toggle
  packages/template-retail-react-app/app/components/_app/index.jsx
  packages/template-retail-react-app/app/components/product-view/index.jsx
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/checkout/confirmation.jsx
  packages/template-retail-react-app/app/pages/checkout/index.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/payment.jsx
  packages/template-retail-react-app/app/pages/checkout/util/checkout-context.js
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/app/pages/product-list/index.jsx
  packages/template-retail-react-app/app/pages/product-list/partials/selected-refinements.jsx
Labels: skip changelog

#2698 U/kzheng/fix skip changelog
  .github/actions/changelog-check/action.yml
Labels: skip changelog
