Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2025-08, with the labels that each got.

#2947 V4 refactor cleanup
  packages/template-chakra-storefront/src/components/seo/index.jsx
  packages/template-chakra-storefront/src/components/seo/index.test.js
  packages/template-chakra-storefront/src/pages/product-detail/hooks/use-product-detail-data.js
  packages/template-chakra-storefront/src/pages/product-detail/index.jsx
  packages/template-chakra-storefront/src/pages/product-list/partials/above-page-header.jsx
  packages/template-chakra-storefront/src/types/config.ts
  packages/template-chakra-storefront/src/types/index.ts
Labels: skip changelog

#2974 @W-19176102 – Fix Apple Pay Token
  packages/template-retail-react-app/app/components/apple-pay-express/index.jsx
Labels: cla:missing

#2841 @W-18998712 Cancel order modal
  packages/template-retail-react-app/app/components/cancel-order-modal/constants.js
  packages/template-retail-react-app/app/components/cancel-order-modal/index.jsx
  packages/template-retail-react-app/app/components/cancel-order-modal/index.test.js
  packages/template-retail-react-app/app/components/product-list/index.jsx
  packages/template-retail-react-app/app/components/product-list/index.test.js
  packages/template-retail-react-app/app/hooks/use-order-products.js
  packages/template-retail-react-app/app/hooks/use-order-products.test.js
  packages/template-retail-react-app/app/pages/account/order-detail.jsx
  packages/template-retail-react-app/app/pages/account/orders.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: ready for review, skip changelog

#2967 @18669235 multiship cart inventory fixes
  packages/template-retail-react-app/app/components/pickup-or-delivery/index.jsx
  packages/template-retail-react-app/app/components/pickup-or-delivery/index.test.jsx
  packages/template-retail-react-app/app/components/product-item-list/index.jsx
  packages/template-retail-react-app/app/components/product-item-list/index.test.jsx
  packages/template-retail-react-app/app/components/product-item/index.jsx
  packages/template-retail-react-app/app/components/product-item/index.test.js
  packages/template-retail-react-app/app/components/product-view/index.jsx
  packages/template-retail-react-app/app/components/unavailable-product-confirmation-modal/index.jsx
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/hooks/use-multiship.test.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.test.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/cart/index.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2976 @W-19119093 - Multiship Shipping Options
  packages/template-retail-react-app/app/pages/checkout/index.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-options-only.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-options.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-options.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-product-cards.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2901 @18981837 search suggestions enhancements v2
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/components/search/index.jsx
  packages/template-retail-react-app/app/components/search/index.test.js
  packages/template-retail-react-app/app/components/search/partials/horizontal-suggestions.jsx
  packages/template-retail-react-app/app/components/search/partials/search-suggestions-section.jsx
  packages/template-retail-react-app/app/components/search/partials/suggestions.jsx
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/app/theme/components/project/search-suggestions.js
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: ready for review

#2979 @W-19207976: Added cursor rules around theming and image manipulation for Agentic Theming POC
  packages/template-retail-react-app/.cursor/rules/comprehensive-header-theming.mdc
  packages/template-retail-react-app/.cursor/rules/header-typography-consistency.mdc
  packages/template-retail-react-app/.cursor/rules/static-asset-management.mdc
  packages/template-retail-react-app/.cursor/rules/theme-colors-rule.mdc
  packages/template-retail-react-app/package.json
Labels: skip changelog

#2994 @W-19250518 : Refactored addToCart modal style into a common theme to be used by new modals.
  packages/template-chakra-storefront/src/hooks/use-add-to-cart-modal.js
  packages/template-chakra-storefront/src/theme/components/project/add-to-cart-modal.js
Labels: ready for review, skip changelog

#2999 fix: add refresh token to shopper agent @W-19097065
  packages/template-retail-react-app/app/components/shopper-agent/index.jsx
  packages/template-retail-react-app/app/components/shopper-agent/index.test.js
  packages/template-retail-react-app/app/hooks/use-miaw.js
  packages/template-retail-react-app/app/hooks/use-refresh-token.js
  packages/template-retail-react-app/app/hooks/use-refresh-token.test.js
Labels: skip changelog

#2966 @W-18670301 - trim with code marker comments
  packages/pwa-kit-create-app/scripts/trim-extensions.js
  packages/pwa-kit-create-app/scripts/trim-extensions.test.js
  packages/pwa-kit-dev/src/configs/webpack/config.js
Labels: skip changelog

#3000 @W-19119093 - Multiship PR review fixes
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-options-list.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-options.jsx
Labels: skip changelog

#2939 @W-19183433: Add code owners validation to the CI pipeline
  .github/workflows/validate-codeowners.yml
Labels: skip changelog

#2997 @W-19169863 – Add Test Coverage to PDP Scenarios
  packages/template-retail-react-app/app/components/apple-pay-express/index.test.jsx
  packages/template-retail-react-app/app/components/express/hooks/use-standalone-payment-methods.test.js
  packages/template-retail-react-app/app/components/express/utils/pdp/basket-calculation.test.js
  packages/template-retail-react-app/app/components/express/utils/pdp/temporary-basket.test.js
Labels: cla:missing

#3015 @W-19168677 feat: set correct pickup addresses for each individual shipment
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.test.js
Labels: skip changelog

#3024 @W-19183335 - Add DEFAULT_SHIPMENT_ID to Constants.js
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.js
Labels: skip changelog

#3030 @W-19097065 - fix: refresh-token-enhancements
  packages/template-retail-react-app/app/components/shopper-agent/index.jsx
  packages/template-retail-react-app/app/components/shopper-agent/index.test.js
Labels: skip changelog

#3023 Storybook with Vite Installation
  package-lock.json
  packages/template-chakra-storefront/.gitignore
  packages/template-chakra-storefront/.storybook/main.js
  packages/template-chakra-storefront/.storybook/manager.js
  packages/template-chakra-storefront/.storybook/preview.jsx
  packages/template-chakra-storefront/package-lock.json
  packages/template-chakra-storefront/package.json
  packages/template-chakra-storefront/vite.config.js
Labels: skip changelog

#3038 @ W-19014920 – Apple Pay PDP Cleanup
  packages/template-retail-react-app/app/components/apple-pay-express/index.jsx
  packages/template-retail-react-app/app/components/apple-pay-express/index.test.jsx
  packages/template-retail-react-app/app/components/express/index.jsx
Labels: cla:missing

#3051 @W-19305118 Put focus on the first digit of the OTP in the modal
  packages/template-retail-react-app/app/components/otp-auth/index.jsx
Labels: skip changelog

#3031 @W-18905072@ - Implement post hook action to release MRT target back to pool
  .github/actions/e2e_release_mrt_target/action.yml
  .github/actions/e2e_release_mrt_target/dist/main.js
  .github/actions/e2e_release_mrt_target/dist/post.js
  .github/workflows/e2e-pr.yml
  .gitignore
  e2e/scripts/mrt-target-manager.js
  e2e/scripts/mrt-target-manager.test.js
Labels: skip changelog

#3044 Align Order Lookup form in the center for Auth users
  packages/template-retail-react-app/app/pages/order-status/index.jsx
  packages/template-retail-react-app/package.json
Labels: ready for review, skip changelog

#3067 @W-19275335 support standard product in bundle
  packages/template-chakra-storefront/mocks/product-bundle.js
  packages/template-chakra-storefront/src/components/product-view-modal/bundle.jsx
  packages/template-chakra-storefront/src/components/product-view/index.jsx
  packages/template-chakra-storefront/src/components/product-view/index.test.js
  packages/template-chakra-storefront/src/hooks/use-add-to-cart-modal.js
  packages/template-chakra-storefront/src/pages/product-detail/hooks/use-product-detail-data.js
  packages/template-chakra-storefront/src/pages/product-detail/index.test.js
  packages/template-chakra-storefront/src/utils/product-utils.js
  packages/template-chakra-storefront/src/utils/product-utils.test.js
Labels: skip changelog

#3058 [CI workflow] automate generating, configurating, and deploying build from `develop` branch (@W-19170135@)
  .github/actions/e2e_generate_app/action.yml
  .github/actions/generate_app/action.yml
  .github/workflows/deploy_latest_release.yml
  .github/workflows/e2e-pr.yml
  .github/workflows/e2e.yml
  .github/workflows/performance-metrics.yml
  .github/workflows/setup_pwa_manual.yml
  e2e/config.js
  e2e/scripts/generate-project.js
  packages/pwa-kit-create-app/assets/bootstrap/js/config/default.js.hbs
  packages/pwa-kit-create-app/assets/bootstrap/js/overrides/app/constants.js.hbs
  packages/pwa-kit-create-app/assets/bootstrap/js/overrides/app/ssr.js.hbs
  packages/pwa-kit-create-app/assets/templates/@salesforce/retail-react-app/app/ssr.js.hbs
  packages/pwa-kit-create-app/assets/templates/@salesforce/retail-react-app/config/default.js.hbs
  packages/pwa-kit-create-app/program.json
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/components/island/README.md
  packages/template-retail-react-app/app/components/island/index.jsx
  packages/template-retail-react-app/app/components/island/index.test.js
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/config/default.js
Labels: skip changelog

#3076 @W-19286198 MULTISHIP fix store address setting
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.test.js
Labels: skip changelog

#3080 @W-19327810 Centralize isPickupShipment logic
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.test.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/checkout/index.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/payment.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.jsx
  packages/template-retail-react-app/app/pages/checkout/util/checkout-context.js
Labels: skip changelog

#3082 @W-19251999 Resend OTP
  packages/template-retail-react-app/app/components/otp-auth/index.jsx
  packages/template-retail-react-app/app/components/otp-auth/index.test.js
  packages/template-retail-react-app/package.json
Labels: skip changelog

#3085 @W-19327810 Replace duplicated logic with isPickupShipment
  packages/template-retail-react-app/app/components/multiship/multiship-order-summary.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipment-details.jsx
Labels: skip changelog

#3084 @W-18905383@ Decouple lint and bundle size GA workflows
  .github/workflows/bundle-size.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: skip changelog

#3086 @W-19263263 [V4 Migration] support standard product in set
  .github/workflows/test.yml
  packages/template-chakra-storefront/src/components/product-view/index.jsx
  packages/template-chakra-storefront/src/components/product-view/index.test.js
  packages/template-chakra-storefront/src/hooks/use-add-to-cart-modal.js
  packages/template-chakra-storefront/src/pages/product-detail/index.test.js
  packages/template-chakra-storefront/src/utils/product-utils.js
  packages/template-chakra-storefront/src/utils/product-utils.test.js
Labels: skip changelog

#3089 @W-19275324 Modify the Product Card to support standard products
  packages/template-chakra-storefront/src/pages/cart/partials/cart-secondary-button-group.jsx
  packages/template-chakra-storefront/src/pages/cart/partials/cart-secondary-button-group.test.js
Labels: ready for review, skip changelog

#3099 @W-19319594 feat: Fix total shipping cost in cart summary when multiple shipments, some free shipping, others charged shipping
  packages/template-retail-react-app/app/components/order-summary/index.jsx
Labels: skip changelog

#3102 @W-19251972 Enable Checkout as Guest for 1cc
  packages/template-retail-react-app/app/components/otp-auth/index.jsx
  packages/template-retail-react-app/app/components/otp-auth/index.test.js
  packages/template-retail-react-app/app/pages/checkout-one-click/index.jsx
  packages/template-retail-react-app/app/pages/checkout-one-click/partials/one-click-contact-info.jsx
  packages/template-retail-react-app/app/pages/checkout-one-click/partials/one-click-payment.jsx
  packages/template-retail-react-app/app/pages/checkout-one-click/partials/one-click-user-registration.jsx
  packages/template-retail-react-app/app/pages/checkout-one-click/partials/one-click-user-registration.test.js
Labels: skip changelog

#2988 @W-19168138 add a new modal to be used for bonus product selection modal
  packages/template-chakra-storefront/src/components/_app/partials/app-layout.jsx
  packages/template-chakra-storefront/src/components/select-bonus-products-button/index.jsx
  packages/template-chakra-storefront/src/hooks/index.js
  packages/template-chakra-storefront/src/hooks/use-add-to-cart-modal.js
  packages/template-chakra-storefront/src/hooks/use-add-to-cart-modal.test.js
  packages/template-chakra-storefront/src/hooks/use-bonus-product-selection-modal.js
  packages/template-chakra-storefront/src/hooks/use-bonus-product-selection-modal.test.js
  packages/template-chakra-storefront/src/hooks/use-modal-state.js
Labels: ready for review, skip changelog

#3100 @W-19339206 feat: add guest address validation before start multi ship
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/utils/address-utils.js
  packages/template-retail-react-app/app/utils/address-utils.test.js
Labels: skip changelog

#3112 @W-19310251 : implement grouping for bonus products with the qualifying product
  packages/template-chakra-storefront/CHANGELOG.md
  packages/template-chakra-storefront/config/default.js
  packages/template-chakra-storefront/src/components/bonus-product-view-modal/index.jsx
  packages/template-chakra-storefront/src/components/product-item/index.jsx
  packages/template-chakra-storefront/src/hooks/use-add-to-cart-modal.test.js
  packages/template-chakra-storefront/src/pages/cart/index.test.js
  packages/template-chakra-storefront/src/pages/cart/partials/cart-product-list-with-grouped-bonus-products.jsx
  packages/template-chakra-storefront/src/pages/cart/partials/cart-product-list.jsx
  packages/template-chakra-storefront/src/pages/cart/partials/select-bonus-products-card.jsx
  packages/template-chakra-storefront/src/utils/bonus-product-utils.js
  packages/template-chakra-storefront/src/utils/bonus-product-utils.test.js
Labels: ready for review

#3124 @W-19347406 feat: fix pickup billing address
  packages/template-retail-react-app/app/pages/checkout/partials/payment.jsx
Labels: skip changelog

#3122 @W-19347489 feat: fix the areAddressesEqual function to include name field comparisons.
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/hooks/use-multiship.test.js
Labels: skip changelog

#3126 [next] Fix this block-end comment
  packages/template-chakra-storefront/src/components/passwordless-login/index.jsx
Labels: skip changelog

#3136 @W-19120760 Display Saved Payment Instruments on Account Page [view only]
  packages/template-retail-react-app/app/assets/svg/credit-card.svg
  packages/template-retail-react-app/app/components/drawer-menu/drawer-menu.jsx
  packages/template-retail-react-app/app/components/header/index.jsx
  packages/template-retail-react-app/app/components/icons/index.jsx
  packages/template-retail-react-app/app/pages/account/constant.js
  packages/template-retail-react-app/app/pages/account/index.jsx
  packages/template-retail-react-app/app/pages/account/payments/index.jsx
  packages/template-retail-react-app/app/pages/account/payments/index.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/config/default.js
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#3094 @W-19000950 Marketing Consent opt-in on Footer email component
  package-lock.json
  package.json
  packages/extension-chakra-store-locator/src/test-utils.jsx
  packages/pwa-kit-create-app/assets/bootstrap/js/overrides/app/components/_app-config/index.jsx.hbs
  packages/template-chakra-storefront/jest.config.js
  packages/template-chakra-storefront/src/components/footer/index.jsx
  packages/template-chakra-storefront/src/components/footer/index.test.js
  packages/template-chakra-storefront/src/components/marketing-consent-card/index.jsx
  packages/template-chakra-storefront/src/components/marketing-consent-card/index.test.jsx
  packages/template-chakra-storefront/src/components/subscription/subscribe-form.jsx
  packages/template-chakra-storefront/src/components/subscription/subscribe-marketing-consent.jsx
  packages/template-chakra-storefront/src/components/subscription/use-subscription.js
  packages/template-chakra-storefront/src/components/subscription/use-subscription.test.js
  packages/template-chakra-storefront/src/constants/marketing-consent.js
  packages/template-chakra-storefront/src/pages/account/index.test.js
  packages/template-chakra-storefront/src/pages/account/profile.jsx
  packages/template-chakra-storefront/src/pages/account/profile.test.js
  packages/template-chakra-storefront/src/static/translations/compiled/en-GB.json
  packages/template-chakra-storefront/src/static/translations/compiled/en-US.json
  packages/template-chakra-storefront/src/static/translations/compiled/en-XA.json
  packages/template-chakra-storefront/src/theme/components/project/footer.js
  packages/template-chakra-storefront/translations/en-GB.json
  packages/template-chakra-storefront/translations/en-US.json
Labels: skip changelog

#3107 @W-19323354 - Add Modal to Find Order Number
  packages/template-retail-react-app/app/components/order-lookup/index.jsx
  packages/template-retail-react-app/app/components/order-lookup/index.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: ready for review, skip changelog

#3129 @W-19168602 - Multiship refactor God hook
  packages/template-retail-react-app/app/hooks/use-item-shipment-management.js
  packages/template-retail-react-app/app/hooks/use-item-shipment-management.test.js
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/hooks/use-multiship.test.js
  packages/template-retail-react-app/app/hooks/use-shipment-operations.js
  packages/template-retail-react-app/app/hooks/use-shipment-operations.test.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/cart/index.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.test.js
  packages/template-retail-react-app/app/utils/shipment-utils.js
  packages/template-retail-react-app/app/utils/shipment-utils.test.js
Labels: skip changelog

#3157 @W-19399002 MULTISHIP refactor pickup hook and address utils
  packages/template-retail-react-app/app/components/multiship/multiship-order-summary.jsx
  packages/template-retail-react-app/app/components/store-locator/list.jsx
  packages/template-retail-react-app/app/hooks/use-item-shipment-management.js
  packages/template-retail-react-app/app/hooks/use-item-shipment-management.test.js
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/hooks/use-multiship.test.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.test.js
  packages/template-retail-react-app/app/hooks/use-shipment-operations.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/cart/index.test.js
  packages/template-retail-react-app/app/pages/checkout/index.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/contact-info.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/payment.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipment-details.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-options.jsx
  packages/template-retail-react-app/app/pages/checkout/util/checkout-context.js
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.test.js
  packages/template-retail-react-app/app/utils/address-utils.js
  packages/template-retail-react-app/app/utils/address-utils.test.js
  packages/template-retail-react-app/app/utils/shipment-utils.js
  packages/template-retail-react-app/app/utils/shipment-utils.test.js
Labels: skip changelog

#3160 @W-19399973 - Reuse ProductItem in Shipping Card
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-product-cards.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#3137 @W-19134205 – Google Pay PDP
  packages/template-retail-react-app/app/components/apple-pay-express/index.jsx
  packages/template-retail-react-app/app/components/express/index.jsx
  packages/template-retail-react-app/app/components/google-pay-express/index.jsx
  packages/template-retail-react-app/app/components/google-pay-express/index.test.jsx
Labels: cla:missing

#3145 @W-19377497 Enable saving payment instruments for registered users
  packages/template-retail-react-app/app/pages/checkout-one-click/index.jsx
  packages/template-retail-react-app/app/pages/checkout-one-click/partials/one-click-payment-form.jsx
  packages/template-retail-react-app/app/pages/checkout-one-click/partials/one-click-payment.jsx
  packages/template-retail-react-app/app/pages/checkout-one-click/partials/one-click-save-payment-method.jsx
  packages/template-retail-react-app/app/pages/checkout-one-click/partials/one-click-save-payment-method.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#3123 @W-19365948 OMS feature flag gating
  packages/template-retail-react-app/app/components/drawer-menu/drawer-menu.jsx
  packages/template-retail-react-app/app/components/drawer-menu/drawer-menu.test.js
  packages/template-retail-react-app/app/components/footer/index.jsx
  packages/template-retail-react-app/app/components/footer/index.test.js
  packages/template-retail-react-app/app/pages/account/order-detail.jsx
  packages/template-retail-react-app/app/pages/account/order-detail.test.jsx
  packages/template-retail-react-app/app/pages/account/orders.test.js
  packages/template-retail-react-app/app/pages/order-status/index.jsx
  packages/template-retail-react-app/app/pages/order-status/index.test.js
  packages/template-retail-react-app/config/default.js
  packages/template-retail-react-app/config/mocks/default.js
Labels: ready for review, skip changelog

#3088 @W-18904979@ - Implement composite actions to update MRT proxy and env vars
  .github/actions/update_mrt_target/action.yml
  .github/workflows/e2e-pr.yml
  e2e/package-lock.json
  e2e/package.json
  e2e/scripts/.env.mrt-env-vars-sample
  e2e/scripts/.env.mrt-settings-sample
  e2e/scripts/update-mrt-target.js
  e2e/scripts/update-mrt-target.test.js
  packages/pwa-kit-mcp/package-lock.json
Labels: ready for review, skip changelog

#3162 @W-19399002 MULTISHIP leverage basket derived data
  packages/template-retail-react-app/app/hooks/use-current-basket.js
  packages/template-retail-react-app/app/hooks/use-current-basket.test.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/checkout/index.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.test.js
  packages/template-retail-react-app/app/pages/checkout/util/checkout-context.js
  packages/template-retail-react-app/package.json
Labels: skip changelog

#3173 Update feature branch with latest changes in `develop`
  packages/commerce-sdk-react/CHANGELOG.md
  packages/commerce-sdk-react/src/auth/index.ts
  packages/commerce-sdk-react/src/components/StorefrontPreview/utils.ts
  packages/commerce-sdk-react/src/constant.ts
  packages/commerce-sdk-react/src/provider.tsx
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/pwa-kit-create-app/assets/bootstrap/js/config/default.js.hbs
  packages/pwa-kit-create-app/assets/bootstrap/js/overrides/app/components/_app-config/index.jsx.hbs
  packages/pwa-kit-create-app/assets/bootstrap/js/overrides/app/main.jsx
  packages/pwa-kit-create-app/assets/bootstrap/js/overrides/app/ssr.js.hbs
  packages/pwa-kit-create-app/assets/templates/@salesforce/retail-react-app/app/components/_app-config/index.jsx.hbs
  packages/pwa-kit-create-app/assets/templates/@salesforce/retail-react-app/app/ssr.js.hbs
  packages/pwa-kit-dev/CHANGELOG.md
  packages/pwa-kit-dev/src/configs/webpack/config.js
  packages/pwa-kit-dev/src/ssr/server/build-dev-server.test.js
  packages/pwa-kit-dev/src/ssr/server/public-path.js
  packages/pwa-kit-react-sdk/CHANGELOG.md
  packages/pwa-kit-react-sdk/src/ssr/universal/utils.js
  packages/pwa-kit-runtime/CHANGELOG.md
  packages/pwa-kit-runtime/jest.config.js
  packages/pwa-kit-runtime/src/ssr/server/build-remote-server.js
  packages/pwa-kit-runtime/src/ssr/server/build-remote-server.test.js
  packages/pwa-kit-runtime/src/ssr/server/express.lambda.test.js
  packages/pwa-kit-runtime/src/ssr/server/express.test.js
  packages/pwa-kit-runtime/src/utils/middleware/security.test.js
  packages/pwa-kit-runtime/src/utils/ssr-namespace-paths.js
  packages/pwa-kit-runtime/src/utils/ssr-namespace-paths.test.js
  packages/pwa-kit-runtime/src/utils/ssr-server.test.js
  packages/pwa-kit-runtime/src/utils/ssr-server/configure-proxy.js
  packages/pwa-kit-runtime/src/utils/ssr-server/convert-express-route.js
  packages/pwa-kit-runtime/src/utils/ssr-server/utils.test.js
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/components/_app-config/index.jsx
  packages/template-retail-react-app/app/hooks/use-active-data.js
  packages/template-retail-react-app/app/hooks/use-auth-modal.js
  packages/template-retail-react-app/app/hooks/use-password-reset.js
  packages/template-retail-react-app/app/main.jsx
  packages/template-retail-react-app/app/page-designer/utils.js
  packages/template-retail-react-app/app/pages/checkout/partials/contact-info.jsx
  packages/template-retail-react-app/app/ssr.js
  packages/template-retail-react-app/app/utils/locale.js
  packages/template-retail-react-app/app/utils/url.js
  packages/template-retail-react-app/app/utils/utils.js
  packages/template-retail-react-app/config/default.js
Labels: skip changelog

#3164 @W-19399362 | Pass Common Payment Context Variables to APay + GPay
  packages/template-retail-react-app/app/api/adyen/paymentMethods/standalone.js
  packages/template-retail-react-app/app/components/apple-pay-express/index.jsx
  packages/template-retail-react-app/app/components/apple-pay-express/index.test.jsx
  packages/template-retail-react-app/app/components/express/hooks/use-express-payment-manager.test.js
  packages/template-retail-react-app/app/components/express/hooks/use-express-payment-setup.js
  packages/template-retail-react-app/app/components/express/hooks/use-standalone-payment-methods.test.js
  packages/template-retail-react-app/app/components/express/index.jsx
  packages/template-retail-react-app/app/components/express/utils/express-payment-utils.js
  packages/template-retail-react-app/app/components/express/utils/express-payment-utils.test.js
  packages/template-retail-react-app/app/components/express/utils/pdp/basket-calculation.test.js
  packages/template-retail-react-app/app/components/express/utils/pdp/temporary-basket.test.js
  packages/template-retail-react-app/app/components/express/utils/shipping-address.test.js
  packages/template-retail-react-app/app/components/express/utils/shipping-methods.test.js
  packages/template-retail-react-app/app/components/google-pay-express/index.jsx
  packages/template-retail-react-app/app/components/google-pay-express/index.test.jsx
Labels: skip changelog

#3166 @W-19365948 add cancel order error handling
  packages/template-retail-react-app/app/pages/account/order-detail.jsx
  packages/template-retail-react-app/app/pages/account/order-detail.test.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/config/default.js
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: ready for review, skip changelog

#2879 Feat: Consume new OAS Isomorphic SDK (@W-19105545@)
  packages/commerce-sdk-react/CHANGELOG.md
  packages/commerce-sdk-react/README.md
  packages/commerce-sdk-react/package-lock.json
  packages/commerce-sdk-react/package.json
  packages/commerce-sdk-react/src/auth/index.test.ts
  packages/commerce-sdk-react/src/auth/index.ts
  packages/commerce-sdk-react/src/components/ShopperExperience/Component/index.test.tsx
  packages/commerce-sdk-react/src/components/ShopperExperience/Region/index.test.tsx
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/helpers.test.tsx
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/index.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/mutation.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperBaskets/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperContexts/mutation.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperContexts/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/index.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/query.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperCustomers/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperExperience/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperGiftCertificates/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperLogin/mutation.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperLogin/query.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperLogin/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperOrders/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperProducts/query.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperProducts/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperPromotions/query.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperPromotions/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperSEO/index.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperSEO/index.ts
  packages/commerce-sdk-react/src/hooks/ShopperSEO/query.test.ts
  packages/commerce-sdk-react/src/hooks/ShopperSEO/query.ts
  packages/commerce-sdk-react/src/hooks/ShopperSEO/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperSearch/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/ShopperStores/queryKeyHelpers.ts
  packages/commerce-sdk-react/src/hooks/index.ts
  packages/commerce-sdk-react/src/hooks/types.ts
  packages/commerce-sdk-react/src/hooks/useQuery.ts
  packages/commerce-sdk-react/src/provider.tsx
  packages/template-mrt-reference-app/package.json
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/package.json
  packages/test-commerce-sdk-react/app/pages/use-product-search.tsx
  packages/test-commerce-sdk-react/app/pages/use-promotions.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-categories.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-orders.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-products.tsx
  packages/test-commerce-sdk-react/app/pages/use-shopper-stores.tsx
  packages/test-commerce-sdk-react/package.json
Labels: skip changelog

#3178 @W-19400384: feat: address comments for https://github.com/SalesforceCommerceCloud/pwa-kit/pull/3150
  packages/template-retail-react-app/app/hooks/use-address-form.js
  packages/template-retail-react-app/app/hooks/use-product-address-assignment.js
  packages/template-retail-react-app/app/hooks/use-product-address-assignment.test.js
  packages/template-retail-react-app/app/hooks/use-shipment-management.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.test.js
  packages/template-retail-react-app/app/utils/address-utils.js
  packages/template-retail-react-app/app/utils/address-utils.test.js
Labels: skip changelog

#3181 @W-19426242 - Refactor Bundle/Set Inventory Logic on PDP
  packages/template-retail-react-app/app/hooks/use-address-form.test.js
  packages/template-retail-react-app/app/hooks/use-product-inventory.js
  packages/template-retail-react-app/app/hooks/use-product-inventory.test.js
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
Labels: skip changelog

#3167 @W-19330619: Update e2e-pr workflow to use MRT target acquired from the pool
  .github/actions/e2e_validate_generated_app/action.yml
  .github/actions/push_to_mrt/action.yml
  .github/workflows/e2e-pr.yml
  e2e/.prettierrc.yaml
  e2e/config.js
  playwright.config.js
Labels: skip changelog

#3180 [A11y E2E] Update a11y snapshots to include unique landmark for toasts
  e2e/tests/a11y/desktop/__snapshots__/guest/cart-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/guest/checkout-a11y-violations-step-0.json
  e2e/tests/a11y/desktop/__snapshots__/guest/checkout-a11y-violations-step-1.json
  e2e/tests/a11y/desktop/__snapshots__/guest/checkout-a11y-violations-step-2.json
  e2e/tests/a11y/desktop/__snapshots__/guest/checkout-a11y-violations-step-3.json
  e2e/tests/a11y/desktop/__snapshots__/guest/checkout-a11y-violations-step-4-order-confirmation.json
  e2e/tests/a11y/desktop/__snapshots__/guest/homepage-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/guest/pdp-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/guest/plp-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/registered/account-addresses-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/registered/account-details-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/registered/checkout-a11y-violations-step-0.json
  e2e/tests/a11y/desktop/__snapshots__/registered/checkout-a11y-violations-step-1.json
  e2e/tests/a11y/desktop/__snapshots__/registered/checkout-a11y-violations-step-2.json
  e2e/tests/a11y/desktop/__snapshots__/registered/checkout-a11y-violations-step-3.json
  e2e/tests/a11y/desktop/__snapshots__/registered/checkout-a11y-violations-step-4-order-confirmation.json
  e2e/tests/a11y/desktop/__snapshots__/registered/order-history-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/registered/wishlist-violations.json
  e2e/tests/a11y/mobile/__snapshots__/guest/plp-a11y-violations.json
  e2e/tests/a11y/mobile/__snapshots__/registered/account-details-a11y-violations.json
Labels: skip changelog

#3185 @W-19426242 - Clean Up Dependencies in Multiship Hooks
  packages/template-retail-react-app/app/hooks/use-address-form.js
  packages/template-retail-react-app/app/hooks/use-address-form.test.js
  packages/template-retail-react-app/app/hooks/use-product-address-assignment.js
  packages/template-retail-react-app/app/hooks/use-product-address-assignment.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
Labels: skip changelog

#3188 @W-19364130 feat: refactor to move shipping cost calculation to derived data, remove unused function, rename files
  packages/template-retail-react-app/app/hooks/use-address-form.js
  packages/template-retail-react-app/app/hooks/use-address-form.test.js
  packages/template-retail-react-app/app/hooks/use-current-basket.js
  packages/template-retail-react-app/app/hooks/use-current-basket.test.js
  packages/template-retail-react-app/app/pages/checkout/index.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-method-options.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-methods.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-methods.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/utils/shipment-utils.js
  packages/template-retail-react-app/app/utils/shipment-utils.test.js
Labels: skip changelog

#3189 @W-19426242 - Refactor Multiship Hooks
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/hooks/use-shipment-management.js
  packages/template-retail-react-app/app/hooks/use-shipment-management.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.test.js
Labels: skip changelog

#3208 [`develop` branch] Bump up the dev versions
  e2e/package-lock.json
  e2e/package.json
  lerna.json
  package-lock.json
  package.json
  packages/commerce-sdk-react/CHANGELOG.md
  packages/commerce-sdk-react/package-lock.json
  packages/commerce-sdk-react/package.json
  packages/internal-lib-build/package-lock.json
  packages/internal-lib-build/package.json
  packages/pwa-kit-create-app/package-lock.json
  packages/pwa-kit-create-app/package.json
  packages/pwa-kit-dev/CHANGELOG.md
  packages/pwa-kit-dev/package-lock.json
  packages/pwa-kit-dev/package.json
  packages/pwa-kit-mcp/package-lock.json
  packages/pwa-kit-mcp/package.json
  packages/pwa-kit-react-sdk/CHANGELOG.md
  packages/pwa-kit-react-sdk/package-lock.json
  packages/pwa-kit-react-sdk/package.json
  packages/pwa-kit-runtime/CHANGELOG.md
  packages/pwa-kit-runtime/package-lock.json
  packages/pwa-kit-runtime/package.json
  packages/template-express-minimal/package-lock.json
  packages/template-express-minimal/package.json
  packages/template-mrt-reference-app/package-lock.json
  packages/template-mrt-reference-app/package.json
  packages/template-retail-react-app/package-lock.json
  packages/template-retail-react-app/package.json
  packages/template-typescript-minimal/package-lock.json
  packages/template-typescript-minimal/package.json
  packages/test-commerce-sdk-react/package-lock.json
  packages/test-commerce-sdk-react/package.json
Labels: skip changelog

#3205 @W-19425482 | Programmatically Style Express Payment Methods
  packages/template-retail-react-app/app/components/apple-pay-express/index.jsx
  packages/template-retail-react-app/app/components/apple-pay-express/index.test.jsx
  packages/template-retail-react-app/app/components/express/index.jsx
  packages/template-retail-react-app/app/components/express/styles/express-payments.css
  packages/template-retail-react-app/app/components/express/utils/express-payment-manager.js
  packages/template-retail-react-app/app/components/google-pay-express/index.jsx
  packages/template-retail-react-app/app/components/google-pay-express/index.test.jsx
Labels: skip changelog

#3214 Restore e2e-PR workflow
  .github/actions/e2e_validate_generated_app/action.yml
  .github/workflows/e2e-pr.yml
  .github/workflows/e2e.yml
  e2e/scripts/pageHelpers.js
  e2e/scripts/validate-generated-project.js
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/guest/cart-a11y-violations.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/guest/checkout-a11y-violations-step-0.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/guest/checkout-a11y-violations-step-1.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/guest/checkout-a11y-violations-step-3.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/guest/checkout-a11y-violations-step-4-order-confirmation.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/guest/homepage-a11y-violations.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/guest/pdp-a11y-violations.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/guest/plp-a11y-violations.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/registered/account-addresses-a11y-violations.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/registered/account-details-a11y-violations.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/registered/checkout-a11y-violations-step-0.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/registered/checkout-a11y-violations-step-1.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/registered/checkout-a11y-violations-step-2.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/registered/checkout-a11y-violations-step-3.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/registered/checkout-a11y-violations-step-4-order-confirmation.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/registered/order-history-a11y-violations.json
  e2e/tests/a11y/desktop/slas-private-client/__snapshots__/registered/wishlist-violations.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/guest/cart-a11y-violations.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/guest/checkout-a11y-violations-step-0.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/guest/checkout-a11y-violations-step-1.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/guest/checkout-a11y-violations-step-2.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/guest/checkout-a11y-violations-step-3.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/guest/checkout-a11y-violations-step-4-order-confirmation.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/guest/homepage-a11y-violations.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/guest/pdp-a11y-violations.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/guest/plp-a11y-violations.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/registered/account-addresses-a11y-violations.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/registered/account-details-a11y-violations.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/registered/checkout-a11y-violations-step-0.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/registered/checkout-a11y-violations-step-1.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/registered/checkout-a11y-violations-step-2.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/registered/checkout-a11y-violations-step-3.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/registered/checkout-a11y-violations-step-4-order-confirmation.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/registered/order-history-a11y-violations.json
  e2e/tests/a11y/desktop/slas-public-client/__snapshots__/registered/wishlist-violations.json
  e2e/tests/a11y/mobile/slas-private-client/__snapshots__/guest/plp-a11y-violations.json
  e2e/tests/a11y/mobile/slas-private-client/__snapshots__/registered/account-details-a11y-violations.json
  e2e/tests/a11y/mobile/slas-public-client/__snapshots__/guest/plp-a11y-violations.json
  e2e/tests/a11y/mobile/slas-public-client/__snapshots__/registered/account-details-a11y-violations.json
  e2e/tests/mobile/guest-shopper.spec.js
  e2e/tests/opentelemetry-b3-tracing.spec.js
  package.json
  playwright.config.js
Labels: skip changelog

#3222 @W-19330454@ [3.12 Release] Fix non-extensible template to use correct passwordless login callback uri
  packages/pwa-kit-create-app/assets/templates/@salesforce/retail-react-app/app/components/_app-config/index.jsx.hbs
Labels: skip changelog
