Repository SalesforceCommerceCloud/pwa-kit, pull requests merged in 2025-07, with the labels that each got.

#2700 @W-18942954 BOPIS revert unneeded swatch change
  packages/template-retail-react-app/app/components/product-view/index.jsx
  packages/template-retail-react-app/app/components/swatch-group/index.jsx
  packages/template-retail-react-app/app/hooks/use-add-to-cart-modal.test.js
Labels: skip changelog

#2707 @W-18934229: PWA Feature Branch Readiness
  packages/pwa-kit-create-app/assets/bootstrap/js/overrides/app/components/_app-config/index.jsx.hbs
  packages/pwa-kit-create-app/assets/bootstrap/js/overrides/app/static/dwac-21.7.js
  packages/pwa-kit-create-app/assets/bootstrap/js/overrides/app/static/dwanalytics-22.2.js
  packages/pwa-kit-create-app/assets/bootstrap/js/overrides/app/static/head-active_data.js
  packages/pwa-kit-dev/src/ssr/server/public-path.js
  packages/pwa-kit-react-sdk/src/ssr/server/react-rendering.js
  packages/pwa-kit-react-sdk/src/ssr/universal/components/with-legacy-get-props/index.js
  packages/pwa-kit-runtime/src/ssr/server/build-remote-server.test.js
  packages/pwa-kit-runtime/src/ssr/server/express.test.js
  packages/pwa-kit-runtime/src/utils/ssr-server.test.js
  packages/template-mrt-reference-app/jest.config.js
  packages/template-retail-react-app/app/components/reset-password/index.test.js
  packages/template-retail-react-app/app/components/unavailable-product-confirmation-modal/index.test.js
  packages/template-retail-react-app/app/pages/account/index.test.js
  packages/template-retail-react-app/app/pages/account/profile.test.js
  packages/template-retail-react-app/app/ssr.js
  packages/test-commerce-sdk-react/app/pages/use-shopper-stores.tsx
Labels: skip changelog

#2699 [🧱 MCP Server Tool] Project Structure Cleanup
  jest.config.cjs
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
  packages/pwa-storefront-mcp/.eslintrc.js
  packages/pwa-storefront-mcp/babel.config.js
  packages/pwa-storefront-mcp/jest-setup.js
  packages/pwa-storefront-mcp/jest.config.js
  packages/pwa-storefront-mcp/package-lock.json
  packages/pwa-storefront-mcp/package.json
  packages/pwa-storefront-mcp/src/server/server.js
  packages/pwa-storefront-mcp/src/server/server.test.js
  packages/pwa-storefront-mcp/src/utils/create-new-component-tool.js
  packages/pwa-storefront-mcp/src/utils/index.js
  packages/pwa-storefront-mcp/src/utils/pwa-create-app-guideline-tool.js
  packages/pwa-storefront-mcp/src/utils/pwa-developer-guideline-tool.js
  packages/pwa-storefront-mcp/src/utils/pwa-developer-guideline-tool.test.js
  packages/pwa-storefront-mcp/src/utils/run-site-test-tool.js
  packages/pwa-storefront-mcp/src/utils/run-site-test-tool.test.js
  packages/pwa-storefront-mcp/src/utils/utils.js
  packages/pwa-storefront-mcp/src/utils/utils.test.js
Labels: skip changelog

#2711 [fix] Generator restructure @W-18895152@
  packages/pwa-kit-create-app/assets/templates/@salesforce/chakra-storefront/config/default.js.hbs
  packages/pwa-kit-create-app/assets/templates/@salesforce/chakra-storefront/config/sites.js.hbs
  packages/pwa-kit-create-app/assets/templates/chakra-storefront/config/default.json.hbs
  packages/pwa-kit-create-app/assets/templates/chakra-storefront/src/components/_app-config/index.jsx.hbs
  packages/pwa-kit-create-app/assets/templates/chakra-storefront/src/ssr.js.hbs
  packages/pwa-kit-create-app/assets/templates/chakra-storefront/src/static/manifest.json.hbs
  packages/pwa-kit-create-app/scripts/create-mobify-app.js
  packages/template-chakra-storefront/config/default.json
  packages/template-chakra-storefront/package.json
Labels: skip changelog

#2653 @W-18818802 add billing phone number to customer on registration
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/pages/checkout/confirmation.jsx
  packages/template-retail-react-app/app/pages/checkout/confirmation.test.js
Labels: skip changelog

#2714 @W-18934229: PWA Feature Branch Readiness
  packages/pwa-kit-create-app/assets/bootstrap/js/config/default.js.hbs
  packages/pwa-kit-create-app/assets/bootstrap/js/config/utils.js.hbs
  packages/pwa-kit-create-app/assets/templates/@salesforce/retail-react-app/config/default.js.hbs
  packages/pwa-kit-create-app/assets/templates/@salesforce/retail-react-app/config/utils.js.hbs
  packages/template-retail-react-app/app/components/_app/index.jsx
  packages/template-retail-react-app/app/components/search/index.jsx
  packages/template-retail-react-app/app/components/search/index.test.js
  packages/template-retail-react-app/config/default.js
  packages/template-retail-react-app/config/mocks/default.js
  packages/template-retail-react-app/config/utils.js
Labels: skip changelog

#2680 Show the Bonus Product in a Product View Modal to enable adding it to the cart
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/components/bonus-product-modal/index.jsx
  packages/template-retail-react-app/app/components/product-view/index.jsx
  packages/template-retail-react-app/app/components/swatch-group/index.jsx
  packages/template-retail-react-app/app/hooks/use-bonus-product-modal.js
  packages/template-retail-react-app/app/hooks/use-bonus-product-modal.test.js
  packages/template-retail-react-app/app/pages/cart/partials/cart-bonus-products.jsx
  packages/template-retail-react-app/app/pages/cart/partials/cart-bonus-products.test.js
Labels: ready for review

#2732 @W-18904649@ - Create a driver workflow for per-PR E2E tests
  .github/workflows/e2e-pr.yml
Labels: skip changelog

#2743 @W-18934229: PWA Feature Branch Readiness
  packages/template-retail-react-app/package.json
Labels: skip changelog

#2704 @ W-18953852: Merge Feature/auto bonus product in to Develop
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/components/item-variant/item-attributes.jsx
  packages/template-retail-react-app/app/components/item-variant/item-attributes.test.js
  packages/template-retail-react-app/app/components/product-item/bonus-product-quantity.jsx
  packages/template-retail-react-app/app/components/product-item/bonus-product-quantity.test.jsx
  packages/template-retail-react-app/app/components/product-item/index.jsx
  packages/template-retail-react-app/app/components/product-item/index.test.js
  packages/template-retail-react-app/app/components/product-item/product-quantity-picker.jsx
  packages/template-retail-react-app/app/components/product-item/product-quantity-picker.test.jsx
  packages/template-retail-react-app/app/mocks/mock-data.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/cart/index.test.js
  packages/template-retail-react-app/app/pages/cart/partials/bonus-products-title.jsx
  packages/template-retail-react-app/app/pages/cart/partials/bonus-products-title.test.js
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.jsx
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: ready for review

#2729 @W-18966462 BOPIS fix product bundles
  packages/template-retail-react-app/app/components/product-view/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
Labels: skip changelog

#2721 @W-18910688 - break down cart page
  packages/extension-chakra-storefront/jest.config.js
  packages/extension-chakra-storefront/src/hooks/cart/use-cart-default-shipping.js
  packages/extension-chakra-storefront/src/hooks/cart/use-cart-gift-items.js
  packages/extension-chakra-storefront/src/hooks/cart/use-cart-gift-items.test.js
  packages/extension-chakra-storefront/src/hooks/cart/use-cart-operations.js
  packages/extension-chakra-storefront/src/hooks/cart/use-cart-operations.test.js
  packages/extension-chakra-storefront/src/hooks/cart/use-cart-products.js
  packages/extension-chakra-storefront/src/hooks/cart/use-cart-products.test.js
  packages/extension-chakra-storefront/src/hooks/cart/use-cart-wishlist.js
  packages/extension-chakra-storefront/src/hooks/cart/use-cart-wishlist.test.js
  packages/extension-chakra-storefront/src/pages/cart/index.jsx
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-modals.jsx
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-modals.test.js
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-product-list.jsx
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-recommendations.jsx
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-secondary-button-group.test.js
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-summary-section.jsx
  packages/extension-chakra-storefront/src/pages/cart/partials/cart-summary-section.test.js
  packages/extension-chakra-storefront/src/pages/cart/partials/empty-cart.test.js
  packages/extension-chakra-storefront/src/pages/cart/utils/cart-utils.js
  packages/extension-chakra-storefront/src/pages/cart/utils/cart-utils.test.js
Labels: skip changelog

#2760 @W-18990330: Made a new Product-List component for cart page
  packages/template-retail-react-app/app/components/product-item-list/index.jsx
  packages/template-retail-react-app/app/components/product-item-list/index.test.jsx
  packages/template-retail-react-app/app/pages/cart/index.jsx
Labels: ready for review, skip changelog

#2781 @W-18910688 - refactored error utils
  packages/extension-chakra-storefront/jest.config.js
  packages/extension-chakra-storefront/src/components/product-view/index.jsx
  packages/extension-chakra-storefront/src/hooks/use-errors.js
  packages/extension-chakra-storefront/src/hooks/use-errors.test.js
  packages/extension-chakra-storefront/src/pages/account/addresses.jsx
  packages/extension-chakra-storefront/src/pages/cart/index.jsx
  packages/extension-chakra-storefront/src/pages/checkout/partials/payment.jsx
  packages/extension-chakra-storefront/src/pages/product-detail/use-product-detail-data.js
  packages/extension-chakra-storefront/src/pages/product-detail/use-product-detail-wishlist.js
Labels: skip changelog

#2702 @W-18909894 - add cursor rules for creating components
  .cursor/rules/storefront-development/component-generation-requirements.mdc
  packages/pwa-kit-create-app/assets/cursor-rules/component-generation-requirements.mdc
  packages/pwa-storefront-mcp/src/server/server.js
Labels: skip changelog

#2786 @W-18737391 Add development guidelines and page creation rules for generated project
  .cursor/rules/storefront-development/component-generation-requirements.mdc
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/pwa-kit-create-app/assets/cursor-rules/development-guidelines.mdc
  packages/pwa-kit-create-app/assets/cursor-rules/page-creation.mdc
  packages/pwa-storefront-mcp/src/utils/pwa-developer-guideline-tool.js
  packages/pwa-storefront-mcp/src/utils/pwa-developer-guideline-tool.test.js
  packages/template-retail-react-app/.cursor/rules/accessibility-rule.mdc
  packages/template-retail-react-app/.cursor/rules/cursor-accessibility-mdc/accessibility-button-name.mdc
  packages/template-retail-react-app/.cursor/rules/cursor-accessibility-mdc/accessibility-heading-order.mdc
  packages/template-retail-react-app/.cursor/rules/cursor-accessibility-mdc/accessibility-image-alt.mdc
  packages/template-retail-react-app/.cursor/rules/cursor-accessibility-mdc/accessibility-input-label.mdc
  packages/template-retail-react-app/.cursor/rules/cursor-accessibility-mdc/accessibility-link-name.mdc
  packages/template-retail-react-app/.cursor/rules/cursor-rule.mdc
  packages/template-retail-react-app/.cursor/rules/development-guidelines.mdc
  packages/template-retail-react-app/.cursor/rules/page-creation.mdc
Labels: skip changelog

#2794 [🧱 MCP Server Tool] Create App Tool Polish 💅
  packages/pwa-kit-create-app/program.json
  packages/pwa-storefront-mcp/jest.config.js
  packages/pwa-storefront-mcp/package-lock.json
  packages/pwa-storefront-mcp/src/server/server.js
  packages/pwa-storefront-mcp/src/server/server.test.js
  packages/pwa-storefront-mcp/src/utils/create-new-component-tool.js
  packages/pwa-storefront-mcp/src/utils/create-new-component-tool.test.js
  packages/pwa-storefront-mcp/src/utils/pwa-create-app-guideline-tool.js
  packages/pwa-storefront-mcp/src/utils/pwa-create-app-guideline-tool.test.js
  packages/pwa-storefront-mcp/src/utils/utils.js
  packages/pwa-storefront-mcp/src/utils/utils.test.js
Labels: skip changelog

#2784 @W-18669182 multiship cart support
  packages/template-retail-react-app/app/components/pickup-or-delivery/index.jsx
  packages/template-retail-react-app/app/components/pickup-or-delivery/index.test.jsx
  packages/template-retail-react-app/app/components/product-item-list/index.jsx
  packages/template-retail-react-app/app/components/product-item/index.jsx
  packages/template-retail-react-app/app/components/store-locator/list.jsx
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/hooks/use-multiship.test.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/cart/partials/bonus-products-title.jsx
  packages/template-retail-react-app/app/pages/cart/partials/order-type-display.jsx
  packages/template-retail-react-app/app/pages/cart/partials/order-type-display.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2815 @W-19053749: Removed edit button for auto-bonus products
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.jsx
  packages/template-retail-react-app/app/pages/cart/partials/cart-secondary-button-group.test.js
Labels: ready for review, skip changelog

#2797 @W-18998921 Feature marketing consent prefs extension
  .eslintrc.js
  global.d.ts
  packages/pwa-kit-create-app/assets/plugin-config.js
  packages/pwa-kit-dev/src/configs/webpack/config.js
  packages/template-chakra-storefront/src/components/marketing-consent-card/index.jsx
  packages/template-chakra-storefront/src/components/marketing-consent-card/index.test.jsx
  packages/template-chakra-storefront/src/pages/account/profile.jsx
  packages/template-chakra-storefront/src/static/translations/compiled/en-US.json
Labels: skip changelog

#2830 @W-18996080 - Add to Cart for Multiship
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/hooks/use-multiship.test.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.js
  packages/template-retail-react-app/app/hooks/use-pickup-shipment.test.js
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.test.js
Labels: skip changelog

#2838 @W-18670301 - plugin flag check
  packages/pwa-kit-create-app/scripts/trim-extensions.js
  packages/pwa-kit-create-app/scripts/trim-extensions.test.js
  packages/template-chakra-storefront/src/pages/home/index.jsx
  packages/template-chakra-storefront/src/pages/login/index.jsx
  packages/template-chakra-storefront/src/pages/registration/index.jsx
  packages/template-chakra-storefront/src/pages/reset-password/index.jsx
Labels: skip changelog

#2827 @W-18998082 - Add a Login form on Order Status Page
  packages/template-retail-react-app/app/components/footer/index.test.js
  packages/template-retail-react-app/app/pages/order-status/index.jsx
  packages/template-retail-react-app/app/pages/order-status/index.test.js
Labels: ready for review, skip changelog

#2860 @W-19085467 – Adyen apple pay update css
  packages/template-retail-react-app/app/components/_app/index.jsx
  packages/template-retail-react-app/app/styles/adyen-overrides.css
Labels: cla:missing

#2852 @W-18910685@ Refactor App Component
  packages/template-chakra-storefront/src/components/_app/hooks/index.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-analytics.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-analytics.test.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-auth.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-auth.test.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-basket.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-basket.test.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-config.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-config.test.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-data.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-data.test.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-localization.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-localization.test.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-modals.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-modals.test.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-navigation.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-navigation.test.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-online-status.js
  packages/template-chakra-storefront/src/components/_app/hooks/use-app-online-status.test.js
  packages/template-chakra-storefront/src/components/_app/index.jsx
  packages/template-chakra-storefront/src/components/_app/index.test.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-footer.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-footer.test.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-header.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-header.test.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-layout.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-layout.test.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-mobile-navigation.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-mobile-navigation.test.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-modals.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-modals.test.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-providers.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-providers.test.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-seo.jsx
  packages/template-chakra-storefront/src/components/_app/partials/app-seo.test.jsx
  packages/template-chakra-storefront/src/components/_app/partials/index.js
Labels: skip changelog

#2866 Feat: Consume new version of `commerce-sdk-isomorphic@3.4.0`
  packages/commerce-sdk-react/CHANGELOG.md
  packages/commerce-sdk-react/package-lock.json
  packages/commerce-sdk-react/package.json
Labels: skip changelog

#2869 @W-19096936 - Handle Shipments on Add to Cart for Bundles
  packages/template-retail-react-app/app/hooks/use-multiship.js
  packages/template-retail-react-app/app/hooks/use-multiship.test.js
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.test.js
Labels: skip changelog

#2877 @W-18981837 merge develop into staging
  packages/commerce-sdk-react/CHANGELOG.md
  packages/commerce-sdk-react/package-lock.json
  packages/commerce-sdk-react/package.json
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/pwa-kit-create-app/program.json
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/components/island/README.md
  packages/template-retail-react-app/app/components/island/index.jsx
  packages/template-retail-react-app/app/components/island/index.test.js
  packages/template-retail-react-app/app/components/product-view-modal/bundle.jsx
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/app/hooks/use-datacloud.js
  packages/template-retail-react-app/app/hooks/use-datacloud.test.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/config/default.js
  packages/template-retail-react-app/config/mocks/default.js
Labels: ready for review, skip changelog

#2884 @W-18998721 Cancelled status pill
  packages/template-retail-react-app/app/pages/account/order-history.jsx
  packages/template-retail-react-app/app/pages/account/order-history.test.js
Labels: ready for review, skip changelog

#2790 @W-18998088 Order tracker on order details page
  packages/template-retail-react-app/app/components/order-status-bar/index.jsx
  packages/template-retail-react-app/app/components/order-status-bar/index.test.js
  packages/template-retail-react-app/app/components/order-status-bar/status-bar.jsx
  packages/template-retail-react-app/app/components/order-status-bar/status-bar.test.js
  packages/template-retail-react-app/app/pages/account/order-detail.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2864 A11y tests - Handle dynamic aria labels generated by chakra UI
  e2e/scripts/utils.js
  e2e/tests/a11y/desktop/__snapshots__/guest/cart-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/guest/checkout-a11y-violations-step-0.json
  e2e/tests/a11y/desktop/__snapshots__/guest/checkout-a11y-violations-step-1.json
  e2e/tests/a11y/desktop/__snapshots__/guest/checkout-a11y-violations-step-2.json
  e2e/tests/a11y/desktop/__snapshots__/guest/checkout-a11y-violations-step-3.json
  e2e/tests/a11y/desktop/__snapshots__/guest/checkout-a11y-violations-step-4-order-confirmation.json
  e2e/tests/a11y/desktop/__snapshots__/guest/homepage-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/guest/pdp-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/guest/plp-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/registered/account-addresses-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/registered/account-details-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/registered/checkout-a11y-violations-step-0.json
  e2e/tests/a11y/desktop/__snapshots__/registered/checkout-a11y-violations-step-1.json
  e2e/tests/a11y/desktop/__snapshots__/registered/checkout-a11y-violations-step-2.json
  e2e/tests/a11y/desktop/__snapshots__/registered/checkout-a11y-violations-step-3.json
  e2e/tests/a11y/desktop/__snapshots__/registered/checkout-a11y-violations-step-4-order-confirmation.json
  e2e/tests/a11y/desktop/__snapshots__/registered/order-history-a11y-violations.json
  e2e/tests/a11y/desktop/__snapshots__/registered/wishlist-violations.json
  e2e/tests/a11y/mobile/__snapshots__/guest/plp-a11y-violations.json
  e2e/tests/a11y/mobile/__snapshots__/registered/account-details-a11y-violations.json
Labels: skip changelog

#2868 @W-18820696 Refactor wishlist hook
  packages/template-chakra-storefront/src/components/_app/partials/app-modals.jsx
  packages/template-chakra-storefront/src/hooks/cart/use-cart-wishlist.js
  packages/template-chakra-storefront/src/hooks/cart/use-cart-wishlist.test.js
  packages/template-chakra-storefront/src/hooks/use-wish-list.js
  packages/template-chakra-storefront/src/hooks/use-wish-list.test.js
  packages/template-chakra-storefront/src/pages/cart/index.jsx
  packages/template-chakra-storefront/src/pages/product-detail/index.test.js
  packages/template-chakra-storefront/src/pages/product-detail/use-product-detail-data.js
  packages/template-chakra-storefront/src/pages/product-detail/use-product-detail-wishlist.js
  packages/template-chakra-storefront/src/pages/product-list/hooks/use-product-list-wishlist.js
  packages/template-chakra-storefront/src/pages/product-list/index.jsx
  packages/template-chakra-storefront/src/utils/utils.js
  packages/template-chakra-storefront/src/utils/utils.test.js
Labels: skip changelog

#2858 @W-18998603 - Add Order Retrieval form on Order Status Page
  packages/template-retail-react-app/app/components/order-lookup/index.jsx
  packages/template-retail-react-app/app/components/order-lookup/index.test.js
  packages/template-retail-react-app/app/pages/order-status/index.jsx
  packages/template-retail-react-app/app/pages/order-status/index.test.js
Labels: ready for review, skip changelog

#2873 Update Order Plugin feature branch with Develop latest
  packages/commerce-sdk-react/CHANGELOG.md
  packages/commerce-sdk-react/package-lock.json
  packages/commerce-sdk-react/package.json
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/pwa-kit-create-app/program.json
  packages/template-retail-react-app/CHANGELOG.md
  packages/template-retail-react-app/app/components/island/README.md
  packages/template-retail-react-app/app/components/island/index.jsx
  packages/template-retail-react-app/app/components/island/index.test.js
  packages/template-retail-react-app/app/components/product-view-modal/bundle.jsx
  packages/template-retail-react-app/app/constants.js
  packages/template-retail-react-app/app/hooks/use-datacloud.js
  packages/template-retail-react-app/app/hooks/use-datacloud.test.js
  packages/template-retail-react-app/app/pages/cart/index.jsx
  packages/template-retail-react-app/app/pages/product-detail/index.jsx
  packages/template-retail-react-app/config/default.js
  packages/template-retail-react-app/config/mocks/default.js
Labels: ready for review, skip changelog

#2859 @W-18670301 - beef up tests
  packages/pwa-kit-create-app/package-lock.json
  packages/pwa-kit-create-app/package.json
  packages/pwa-kit-create-app/scripts/trim-extensions.test.js
Labels: skip changelog

#2896 @W-18996216 - Enhance create page mcp tool by adding Image Component support
  packages/pwa-storefront-mcp/src/server/server.js
  packages/pwa-storefront-mcp/src/utils/create-new-component-tool.js
  packages/pwa-storefront-mcp/src/utils/create-new-page-tool.js
  packages/pwa-storefront-mcp/src/utils/create-new-page-tool.test.js
  packages/pwa-storefront-mcp/src/utils/utils.js
Labels: skip changelog

#2895 Support Translation and accessibility on Order Status Page
  packages/template-retail-react-app/app/components/forms/use-order-lookup-fields.jsx
  packages/template-retail-react-app/app/components/order-lookup/index.jsx
  packages/template-retail-react-app/app/components/order-lookup/index.test.js
  packages/template-retail-react-app/app/pages/order-status/index.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: ready for review, skip changelog

#2905 Fix/next branch bundle upload
  packages/pwa-kit-dev/bin/pwa-kit-dev.js
  packages/pwa-kit-dev/src/configs/webpack/config.js
  packages/template-chakra-storefront/static/README.md
Labels: skip changelog

#2876 @W-18927217: New component for user registration
  packages/template-retail-react-app/app/hooks/use-toast.js
  packages/template-retail-react-app/app/pages/checkout-one-click/index.jsx
  packages/template-retail-react-app/app/pages/checkout-one-click/index.test.js
  packages/template-retail-react-app/app/pages/checkout-one-click/partials/one-click-payment.jsx
  packages/template-retail-react-app/app/pages/checkout-one-click/partials/one-click-user-registration.jsx
  packages/template-retail-react-app/app/pages/confirmation/index.jsx
  packages/template-retail-react-app/app/pages/confirmation/index.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/app/utils/password-utils.js
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2909 @W-19013822 - Multiship Add New Address missing l10n files
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2911 Fix: Enabling Streaming on MIAW
  packages/pwa-kit-create-app/CHANGELOG.md
  packages/template-retail-react-app/app/hooks/use-miaw.js
Labels: skip changelog

#2938 [V4] Make sure that the server side rendering works again (@W-19159606@)
  packages/pwa-kit-react-sdk/CHANGELOG.md
  packages/pwa-kit-react-sdk/src/ssr/server/react-rendering.js
  packages/pwa-kit-react-sdk/src/ssr/universal/components/with-react-query/index.js
Labels: skip changelog

#2902 Add Order Status in Mobile Menu
  packages/template-retail-react-app/app/components/drawer-menu/drawer-menu.jsx
  packages/template-retail-react-app/app/components/drawer-menu/drawer-menu.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: ready for review, skip changelog

#2921 Update codeowners file to include ownership for specific features
  .github/CODEOWNERS
Labels: skip changelog

#2875 @W-19065083 feat: Handle multi-pickup shipments in checkout when multiple pickup and/or delivery shipments
  packages/template-retail-react-app/app/components/item-variant/item-attributes.jsx
  packages/template-retail-react-app/app/components/order-summary/index.jsx
  packages/template-retail-react-app/app/components/product-item-list/checkout-product-item-list.jsx
  packages/template-retail-react-app/app/components/product-item/checkout-product-item.jsx
  packages/template-retail-react-app/app/pages/checkout/index.jsx
  packages/template-retail-react-app/app/pages/checkout/index.test.js
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/pickup-address.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2935 MultiShip Add New Address button
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.test.js
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2950 Fix: Select Address dropdown
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/static/translations/compiled/en-GB.json
  packages/template-retail-react-app/app/static/translations/compiled/en-US.json
  packages/template-retail-react-app/app/static/translations/compiled/en-XA.json
  packages/template-retail-react-app/translations/en-GB.json
  packages/template-retail-react-app/translations/en-US.json
Labels: skip changelog

#2959 @W-19175835 - Show Only Delivery Items in Multiship View
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.jsx
  packages/template-retail-react-app/app/pages/checkout/partials/shipping-multi-address.test.js
Labels: skip changelog

#2854 @W-18954321@ - Update USID expiry to match SLAS refresh token expiry
  packages/commerce-sdk-react/CHANGELOG.md
  packages/commerce-sdk-react/src/auth/index.test.ts
  packages/commerce-sdk-react/src/auth/index.ts
Labels: ready for review

#2927 Fix eslint discoverability in the monorepo (@W-19068681@)
  package-lock.json
  package.json
  scripts/check-eslint-deps.js
Labels: skip changelog

#2946 @W-19013916 - Committing for Rules and cleanup
  packages/pwa-kit-mcp/src/tools/create-new-page-tool.js
  packages/template-retail-react-app/.cursor/rules/component-generation-requirements.mdc
  packages/template-retail-react-app/.cursor/rules/page-creation.mdc
Labels: skip changelog
